/* <<< Look_Def.h >>> */

#ifndef __LOOK_DEF__
#define __LOOK_DEF__

#include "look_grf.h"


#define LOOK_DEF_COL     \
                         BLUE,MAGENTA,\
                         WHITE,WHITE,BLUE,\
                         BLACK,LIGHTGRAY,\
                         LIGHTCYAN,BLUE,\
                         GREEN,\
                         YELLOW,LIGHTGREEN,LIGHTGRAY

#define LOOK_DEF_COL1    \
                         BLUE,CYAN,\
                         WHITE,WHITE,BLUE,\
                         BLACK,LIGHTGRAY,\
                         LIGHTCYAN,BLUE,\
                         BLACK,\
                         YELLOW,LIGHTGREEN,BLACK

#define LOOK_DEF_COL2    \
                         BLUE,CYAN,\
                         WHITE,WHITE,BLUE,\
                         BLACK,LIGHTGRAY,\
                         LIGHTCYAN,BLUE,\
                         BLACK,\
                         YELLOW,LIGHTGREEN,BLACK

#define LOOK_DEF_COL3    \
                         BROWN,CYAN,\
                         WHITE,WHITE,BLUE,\
                         BLACK,LIGHTGRAY,\
                         LIGHTCYAN,BLUE,\
                         MAGENTA,\
                         YELLOW,LIGHTGREEN,YELLOW



#define FULL_SCR {  5,  5,995,995,LOOK_DEF_COL1}

#define VER_1_2  {  5,  5,495,995,LOOK_DEF_COL1}
#define VER_2_2  {505,  5,995,995,LOOK_DEF_COL2}

#define HOR_2_2  {  5,  5,995,495,LOOK_DEF_COL1}
#define HOR_1_2  {  5,505,995,995,LOOK_DEF_COL2}

#define BOX_4_4  {505,  5,995,495,LOOK_DEF_COL1}
#define BOX_3_4  {  5,  5,495,495,LOOK_DEF_COL1}
#define BOX_2_4  {505,505,995,995,LOOK_DEF_COL1}
#define BOX_1_4  {  5,505,495,995,LOOK_DEF_COL1}

#define BOX_6_6  {665,  5,995,495,LOOK_DEF_COL1}
#define BOX_5_6  {335,  5,665,495,LOOK_DEF_COL1}
#define BOX_4_6  {  5,  5,330,495,LOOK_DEF_COL1}
#define BOX_3_6  {665,455,995,995,LOOK_DEF_COL1}
#define BOX_2_6  {335,455,665,995,LOOK_DEF_COL1}
#define BOX_1_6  {  5,455,330,995,LOOK_DEF_COL1}

#define BOX_8_8  {755,  5,995,495,LOOK_DEF_COL1}
#define BOX_7_8  {505,  5,750,495,LOOK_DEF_COL1}
#define BOX_6_8  {255,  5,500,495,LOOK_DEF_COL1}
#define BOX_5_8  {  5,  5,250,495,LOOK_DEF_COL1}
#define BOX_4_8  {755,455,995,995,LOOK_DEF_COL1}
#define BOX_3_8  {505,455,750,995,LOOK_DEF_COL1}
#define BOX_2_8  {255,455,500,995,LOOK_DEF_COL1}
#define BOX_1_8  {  5,455,250,995,LOOK_DEF_COL1}


#define FULL_SCR_T {  5,  5,995,895,LOOK_DEF_COL1}

#define VER_1_2_T  {  5,  5,495,895,LOOK_DEF_COL1}
#define VER_2_2_T  {505,  5,995,895,LOOK_DEF_COL2}

#define HOR_2_2_T  {  5,  5,995,445,LOOK_DEF_COL1}
#define HOR_1_2_T  {  5,455,995,895,LOOK_DEF_COL2}

#define BOX_4_4_T  {505,  5,995,445,LOOK_DEF_COL1}
#define BOX_3_4_T  {  5,  5,495,445,LOOK_DEF_COL1}
#define BOX_2_4_T  {505,455,995,895,LOOK_DEF_COL1}
#define BOX_1_4_T  {  5,455,495,895,LOOK_DEF_COL1}

#define BOX_6_6_T  {665,  5,995,445,LOOK_DEF_COL1}
#define BOX_5_6_T  {335,  5,665,445,LOOK_DEF_COL1}
#define BOX_4_6_T  {  5,  5,330,445,LOOK_DEF_COL1}
#define BOX_3_6_T  {665,455,995,895,LOOK_DEF_COL1}
#define BOX_2_6_T  {335,455,665,895,LOOK_DEF_COL1}
#define BOX_1_6_T  {  5,455,330,895,LOOK_DEF_COL1}

#define BOX_8_8_T  {755,  5,995,445,LOOK_DEF_COL1}
#define BOX_7_8_T  {505,  5,750,445,LOOK_DEF_COL1}
#define BOX_6_8_T  {255,  5,500,445,LOOK_DEF_COL1}
#define BOX_5_8_T  {  5,  5,250,445,LOOK_DEF_COL1}
#define BOX_4_8_T  {755,455,995,895,LOOK_DEF_COL1}
#define BOX_3_8_T  {505,455,750,895,LOOK_DEF_COL1}
#define BOX_2_8_T  {255,455,500,895,LOOK_DEF_COL1}
#define BOX_1_8_T  {  5,455,250,895,LOOK_DEF_COL1}


#define ADD_1  {0,0,0,0, BLUE}
#define ADD_2  {0,0,0,0, MAGENTA}
#define ADD_3  {0,0,0,0, RED}
#define ADD_4  {0,0,0,0, BROWN}
#define ADD_5  {0,0,0,0, LIGHTBLUE}
#define ADD_6  {0,0,0,0, LIGHTGREEN}
#define ADD_7  {0,0,0,0, LIGHTRED}
#define ADD_8  {0,0,0,0, LIGHTMAGENTA}
#define ADD_9  {0,0,0,0, YELLOW}


#endif


