

/*
 *   Generated by  UI v2.00
 *        February 3, 1997
 */


/* Module: E:\WORK\VAZ\4K\WW\ADA_4SYS.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "pro_achh.h"
#include <process.h>
#define Nil _nil_EXEC




#define HelpFileName getHelpFile()



VOID  CTYP _startup_EXEC(NOARG);
VOID  CTYP _shutdown_EXEC(NOARG);
VOID  CTYP _savecfg_EXEC(NOARG);
VOID  CTYP _do_init_EXEC(NOARG);
VOID  CTYP _nil_EXEC(NOARG);
VOID  CTYP _loadcfg_EXEC(NOARG);
KeyT  CTYP _et_s_MENU(NOARG);
KeyT  CTYP _wid_upr_MENU(NOARG);
VOID  CTYP _SETCHECK_EXEC(NOARG);
VOID  CTYP _file_et_ENTRY(NOARG);
VOID  CTYP _ifile_et_ENTRY(NOARG);
VOID  CTYP _file_upr_ENTRY(NOARG);
VOID  CTYP _wybor_EXEC(NOARG);
VOID  CTYP _sel_file_et_SELECT(NOARG);
VOID  CTYP _write_et_EXEC(NOARG);
VOID  CTYP _sel_ifile_et_SELECT(NOARG);
VOID  CTYP _write_upr_EXEC(NOARG);
VOID  CTYP _sel_file_upr_SELECT(NOARG);
VOID  CTYP _xsel_file_et_EXEC(NOARG);
VOID  CTYP _xsel_ifile_et_EXEC(NOARG);
VOID  CTYP _xsel_file_upr_EXEC(NOARG);
VOID CTYP _background_2STR(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);
VOID CTYP _et_s_2STR(NOARG);
VOID CTYP _et_s_MSG(NOARG);
VOID CTYP _wid_upr_2STR(NOARG);
VOID CTYP _wid_upr_MSG(NOARG);
VOID CTYP _file_et_2STR(NOARG);
VOID CTYP _file_et_OPEN(NOARG);
VOID CTYP _ifile_et_2STR(NOARG);
VOID CTYP _ifile_et_OPEN(NOARG);
VOID CTYP _file_upr_2STR(NOARG);
VOID CTYP _file_upr_OPEN(NOARG);
VOID CTYP _sel_file_et_2STR(NOARG);
VOID CTYP _sel_file_et_MSG(NOARG);
VOID CTYP _sel_ifile_et_2STR(NOARG);
VOID CTYP _sel_ifile_et_MSG(NOARG);
VOID CTYP _sel_file_upr_2STR(NOARG);
VOID CTYP _sel_file_upr_MSG(NOARG);


LCL VOID CTYP _opt1_ACT(NOARG)
{
sys_har();
return;
}

LCL VOID CTYP _opt2_ACT(NOARG)
{
MOD_PODS();
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
sys_test();
return;
}

LCL IbldT _main_Itm[]={
{" Система ",'\0',ITM_NOR,0,0,  1,HLP_NONE,
   0,2,NULL,_opt1_ACT,NULL,
   NULL,NULL},
{" Модели_подстройки ",'\0',ITM_NOR,0,10,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   NULL,NULL},
{" Эталонный_сигнал ",'\0',ITM_NOR,0,30,  5,HLP_NONE,
   0,6,NULL,_et_s_MENU,NULL,
   NULL,NULL},
{" Анализ_объекта ",'\0',ITM_NOR,0,49,  7,HLP_NONE,
   0,8,NULL,_opt4_ACT,NULL,
   NULL,NULL},
{" Управление ",'\0',ITM_NOR,0,66,  9,HLP_NONE,
   0,10,NULL,_wid_upr_MENU,NULL,
   NULL,NULL},
};


LCL VOID CTYP _main_MSG(NOARG);
LCL MbldT _main_Mnu={
   _main_Itm,5,1,0,3,79,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_main_MSG,11, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _main_MSG(NOARG)
{

 CurHide();
  Wmessage("\020" "",BRD_TOP,26,_BLUE|INTENSE|LGREY);
  Wmessage(" Управление стендом (4x4) ",BRD_TOP,27,_LGREY|BLUE);
  Wmessage("\021" "",BRD_TOP,53,_BLUE|INTENSE|LGREY);
  {
  MnuDsp(&_main_Mnu);
  }
 KbndSet(Key_A_X,(VfvCP)_shutdown_EXEC,0);
 KbndSet(Key_F2,(VfvCP)_savecfg_EXEC,0);
 KbndSet(Key_Esc,(VfvCP)_nil_EXEC,0);
 KbndSet(Key_F3,(VfvCP)_loadcfg_EXEC,0);
  return;
}
LCL VOID CTYP _startup_EXEC(NOARG)
{
StartUp();      
xLoadCfg(NULL); 
WsetFil('░');   
                
  return;
}
LCL VOID CTYP _shutdown_EXEC(NOARG)
{
ShutDown(); xSaveCfg(NULL);                                                   
WcloseAll();                                                                  
#ifdef __TURBOC__                                                             
 _cexit();                                                                    
#endif                                                                        
printf("\nАдаптивное управление стендовым оборудованием"                      
       "\nРазработка ПКЦ \"Системы-Триал\" (C) 1995-97"                       
       "\nПоследняя редакция от <" __DATE__ ">"                               
       "\n");                                                                 
                                                                              
exit(0);                                                                      
  return;
}
LCL VOID CTYP _savecfg_EXEC(NOARG)
{
SaveCfg();    
              
  return;
}
LCL VOID CTYP _do_init_EXEC(NOARG)
{
                    
WsetFil(' ');       
  return;
}
LCL VOID CTYP _nil_EXEC(NOARG)
{
// Ничего  
  return;
}
LCL VOID CTYP _loadcfg_EXEC(NOARG)
{
LoadCfg();    
              
  return;
}

LCL VOID CTYP _opt6_ACT(NOARG)
{
poly_sin();
return;
}

LCL VOID CTYP _opt10_ACT(NOARG)
{
from_stend();
return;
}

LCL VOID CTYP _opt11_ACT(NOARG)
{
vi_et_graph();
return;
}

LCL IbldT _et_s_Itm[]={
{"   Полигармоника ",'\0',ITM_NOR,1,2,  12,HLP_NONE,
   0,13,NULL,_opt6_ACT,NULL,
   NULL,NULL},
{"   Из файла      ",'\0',ITM_NOR,2,2,  14,HLP_NONE,
   0,15,NULL,_file_et_ENTRY,NULL,
   NULL,NULL},
{"   Со стенда     ",'\0',ITM_NOR,3,2,  16,HLP_NONE,
   0,17,NULL,_opt10_ACT,NULL,
   NULL,NULL},
{" В виде графиков ",'\0',ITM_NOR,5,2,  18,HLP_NONE,
   0,19,NULL,_opt11_ACT,NULL,
   NULL,NULL},
{"     В файл      ",'\0',ITM_NOR,6,2,  20,HLP_NONE,
   0,21,NULL,_ifile_et_ENTRY,NULL,
   NULL,NULL},
};


LCL VOID CTYP _et_s_MSG(NOARG);
LCL MbldT _et_s_Mnu={
   _et_s_Itm,5,4,31,13,53,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_et_s_MSG,22, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _et_s_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,0,_BLUE|INTENSE|BROWN,"┌────\020" " Задание \021" "────┐");
  Wprts(1,0,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,20,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,0,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,20,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,0,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,20,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,0,_BLUE|INTENSE|BROWN,"├───\020" " Просмотр \021" "────┤");
  Wprts(5,0,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,20,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,0,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,20,_BLUE|INTENSE|BROWN,"│");
  Wprts(7,0,_BLUE|INTENSE|BROWN,"└───────────────────┘");
  {
  MnuDsp(&_et_s_Mnu);
  }
  return;
}
LCL KeyT CTYP _et_s_MENU(NOARG)
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  _SETCHECK_EXEC();

 MnuBuild(&_et_s_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}

LCL VOID CTYP _opt7_ACT(NOARG)
{
Loop();
return;
}

LCL VOID CTYP _opt9_ACT(NOARG)
{
GotoNull();
return;
}

LCL VOID CTYP _opt12_ACT(NOARG)
{
graf_time();
return;
}

LCL VOID CTYP _opt14_ACT(NOARG)
{
graf_2time();
return;
}

LCL IbldT _wid_upr_Itm[]={
{"  Запуск эксперимента   ",'\0',ITM_NOR,1,2,  23,HLP_NONE,
   0,24,NULL,_opt7_ACT,NULL,
   NULL,NULL},
{" Тест тракта управления ",'\0',ITM_NOR,2,2,  25,HLP_NONE,
   0,26,NULL,_opt9_ACT,NULL,
   NULL,NULL},
{"  Графики (вход/выход)  ",'\0',ITM_NOR,5,2,  27,HLP_NONE,
   0,28,NULL,_opt12_ACT,NULL,
   NULL,NULL},
{" Графики (эталон/выход) ",'\0',ITM_NOR,6,2,  29,HLP_NONE,
   0,30,NULL,_opt14_ACT,NULL,
   NULL,NULL},
{"     Запись в файл      ",'\0',ITM_NOR,7,2,  31,HLP_NONE,
   0,32,NULL,_file_upr_ENTRY,NULL,
   NULL,NULL},
};


LCL VOID CTYP _wid_upr_MSG(NOARG);
LCL MbldT _wid_upr_Mnu={
   _wid_upr_Itm,5,4,48,14,77,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_wid_upr_MSG,33, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _wid_upr_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,1,_BLUE|INTENSE|BROWN,"┌");
  Wprts(0,2,_BLUE|INTENSE|LGREY,"─");
  Wprts(0,3,_BLUE|INTENSE|BROWN,"─────\020" " Стенд \021" "─────────");
  Wprts(0,26,_BLUE|INTENSE|LGREY,"┐");
  Wprts(1,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,1,_BLUE|INTENSE|BROWN,"└────────────────────────┘");
  Wprts(4,1,_BLUE|INTENSE|BROWN,"┌────\020" " Результаты \021" "──────┐");
  Wprts(5,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(7,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(7,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(8,1,_BLUE|INTENSE|BROWN,"└────────────────────────┘");
  {
  MnuDsp(&_wid_upr_Mnu);
  }
  return;
}
LCL KeyT CTYP _wid_upr_MENU(NOARG)
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_wid_upr_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}
LCL VOID CTYP _SETCHECK_EXEC(NOARG)
{
// extern IbldT _wid_et_s_Itm[];                    
IdfStr(&_et_s_Itm[Cfg.Def[0].tplCod-1])[1]='√';     
                                                    
  return;
}

LCL ChrT file_et_var1[16];
LCL ChrT file_et_var6[6];
LCL ChrT file_et_var7[6];
LCL ChrT file_et_var8[6];
LCL ChrT file_et_var9[6];
LCL ChrT file_et_var10[6];
LCL ChrT file_et_var11[6];
LCL ChrT file_et_var12[6];
LCL ChrT file_et_var13[6];
LCL FbldT _file_et_Fld[]={
 {"",0,0, file_et_var1,1,12,
  "***************",NULL,NULL,NULL,
  0,34,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, file_et_var6,6,7,
  "99.99",NULL,NULL,NULL,
  0,35,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var7,6,17,
  "99.99",NULL,NULL,NULL,
  0,36,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var8,7,7,
  "99.99",NULL,NULL,NULL,
  0,37,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var9,7,17,
  "99.99",NULL,NULL,NULL,
  0,38,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var10,8,7,
  "99.99",NULL,NULL,NULL,
  0,39,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var11,8,17,
  "99.99",NULL,NULL,NULL,
  0,40,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var12,9,7,
  "99.99",NULL,NULL,NULL,
  0,41,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var13,9,17,
  "99.99",NULL,NULL,NULL,
  0,42,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _file_et_Frm={
 _file_et_Fld,9,NULL,NULL,43,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _file_et_OPEN(NOARG)
{

 Wopen(8,33,19,62,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " Эталон из файла \021" "",BRD_TOP,6,_MAGENTA|INTENSE|GREEN);
  Wmessage("┤                 ├",BRD_BOT,2,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");
  Wprts(3,0,_CYAN|BLACK,"─────┬───────┬──────────────");
  Wprts(4,0,_CYAN|BLACK,"Канал│Статика│Коэффициент");
  Wprts(5,0,_CYAN|BLACK,"─────┼───────┼──────────────");
  Wprts(6,2,_CYAN|BLACK,"1");
  Wprts(6,5,_CYAN|BLACK,"│");
  Wprts(6,13,_CYAN|BLACK,"│");
  Wprts(7,2,_CYAN|BLACK,"2");
  Wprts(7,5,_CYAN|BLACK,"│");
  Wprts(7,13,_CYAN|BLACK,"│");
  Wprts(8,2,_CYAN|BLACK,"3");
  Wprts(8,5,_CYAN|BLACK,"│");
  Wprts(8,13,_CYAN|BLACK,"│");
  Wprts(9,2,_CYAN|BLACK,"4");
  Wprts(9,5,_CYAN|BLACK,"│");
  Wprts(9,13,_CYAN|BLACK,"│");

  _file_et_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_file_et_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _file_et_2STR(NOARG)
{
  strcpy(file_et_var1,Cfg.Def[0].file_name); strsetsz(file_et_var1,15);
  cvtfc(file_et_var6,Cfg.Def[0].file_st,5,2);
  cvtfc(file_et_var7,Cfg.Def[0].file_k,5,2);
  cvtfc(file_et_var8,Cfg.Def[1].file_st,5,2);
  cvtfc(file_et_var9,Cfg.Def[1].file_k,5,2);
  cvtfc(file_et_var10,Cfg.Def[2].file_st,5,2);
  cvtfc(file_et_var11,Cfg.Def[2].file_k,5,2);
  cvtfc(file_et_var12,Cfg.Def[3].file_st,5,2);
  cvtfc(file_et_var13,Cfg.Def[3].file_k,5,2);
 return;
}
LCL VOID CTYP _file_et_2VAL(NOARG)
{
    strcpy(Cfg.Def[0].file_name,file_et_var1);
    Cfg.Def[0].file_st=cvtcf(file_et_var6);
    Cfg.Def[0].file_k=cvtcf(file_et_var7);
    Cfg.Def[1].file_st=cvtcf(file_et_var8);
    Cfg.Def[1].file_k=cvtcf(file_et_var9);
    Cfg.Def[2].file_st=cvtcf(file_et_var10);
    Cfg.Def[2].file_k=cvtcf(file_et_var11);
    Cfg.Def[3].file_st=cvtcf(file_et_var12);
    Cfg.Def[3].file_k=cvtcf(file_et_var13);
 return;
}

LCL VOID CTYP _file_et_ENTRY(NOARG)
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _file_et_OPEN();
 KbndSet(Key_F3,(VfvCP)_sel_file_et_SELECT,0);
 KbndMou(Key_M_ClkL,(VfvCP)_sel_file_et_SELECT,19,36,17);
  Vputn(19,36,"",_MAGENTA|INTENSE|GREEN,17);
  Vprints(19,37,_MAGENTA|INTENSE|LGREY,"F3");
  Vprints(19,39,_MAGENTA|INTENSE|GREEN,"-Список");
  Vprints(19,47,_MAGENTA|INTENSE|GREEN,"*.TEM");
 _file_et_2STR();
 if(e) EntPush();
 EntBuild(&_file_et_Frm);
 CurShow();
 val=EntGet(_file_et_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _file_et_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
  _wybor_EXEC();
 EntResult=tmp;
}

LCL ChrT ifile_et_var5[16];
LCL FbldT _ifile_et_Fld[]={
 {"",0,0, ifile_et_var5,1,12,
  "***************",NULL,NULL,NULL,
  0,44,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _ifile_et_Frm={
 _ifile_et_Fld,1,NULL,NULL,45,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _ifile_et_OPEN(NOARG)
{

 Wopen(13,28,17,57,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " Эталон в файл \021" "",BRD_TOP,6,_MAGENTA|INTENSE|GREEN);
  Wmessage("┤                 ├",BRD_BOT,2,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");

  _ifile_et_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_ifile_et_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _ifile_et_2STR(NOARG)
{
  strcpy(ifile_et_var5,Cfg.ifile_name); strsetsz(ifile_et_var5,15);
 return;
}
LCL VOID CTYP _ifile_et_2VAL(NOARG)
{
    strcpy(Cfg.ifile_name,ifile_et_var5);
 return;
}

LCL VOID CTYP _ifile_et_ENTRY(NOARG)
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _ifile_et_OPEN();
 KbndSet(Key_F3,(VfvCP)_sel_ifile_et_SELECT,0);
 KbndMou(Key_M_ClkL,(VfvCP)_sel_ifile_et_SELECT,17,31,17);
  Vputn(17,31,"",_MAGENTA|INTENSE|GREEN,17);
  Vprints(17,32,_MAGENTA|INTENSE|LGREY,"F3");
  Vprints(17,34,_MAGENTA|INTENSE|GREEN,"-Список");
  Vprints(17,42,_MAGENTA|INTENSE|GREEN,"*.TEM");
 _ifile_et_2STR();
 if(e) EntPush();
 EntBuild(&_ifile_et_Frm);
 CurShow();
 val=EntGet(_ifile_et_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _ifile_et_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
  _write_et_EXEC();
 EntResult=tmp;
}

LCL ChrT file_upr_var14[16];
LCL FbldT _file_upr_Fld[]={
 {"",0,0, file_upr_var14,1,12,
  "***************",NULL,NULL,NULL,
  0,46,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _file_upr_Frm={
 _file_upr_Fld,1,NULL,NULL,47,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _file_upr_OPEN(NOARG)
{

 Wopen(18,37,22,66,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " Управление в файл \021" "",BRD_TOP,3,_MAGENTA|INTENSE|GREEN);
  Wmessage("┤                ├",BRD_BOT,2,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");

  _file_upr_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_file_upr_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _file_upr_2STR(NOARG)
{
  strcpy(file_upr_var14,Cfg.ufile_name); strsetsz(file_upr_var14,15);
 return;
}
LCL VOID CTYP _file_upr_2VAL(NOARG)
{
    strcpy(Cfg.ufile_name,file_upr_var14);
 return;
}

LCL VOID CTYP _file_upr_ENTRY(NOARG)
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _file_upr_OPEN();
 KbndSet(Key_F3,(VfvCP)_sel_file_upr_SELECT,0);
 KbndMou(Key_M_ClkL,(VfvCP)_sel_file_upr_SELECT,22,40,16);
  Vputn(22,40,"",_MAGENTA|INTENSE|GREEN,16);
  Vprints(22,40,_MAGENTA|INTENSE|LGREY,"F3");
  Vprints(22,42,_MAGENTA|INTENSE|GREEN,"-Список");
  Vprints(22,50,_MAGENTA|INTENSE|GREEN,"*.UPR");
 _file_upr_2STR();
 if(e) EntPush();
 EntBuild(&_file_upr_Frm);
 CurShow();
 val=EntGet(_file_upr_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _file_upr_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
  _write_upr_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _wybor_EXEC(NOARG)
{
if(EntResult) {              
   Cfg.Def[0].tplCod=2;      
   SetCheck(MctlTag);        
   }                         
  return;
}
LCL VOID CTYP _sel_file_et_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL ChrT et_tmp[65];
LCL VOID CTYP _sel_file_et_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP sel_file_et_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOff();
  SelParOff();
  sel_file_et_file=SelFile(11,16,22,60,BOX_VER,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_BLUE|INTENSE|GREEN,
          1,"*.TEM",_sel_file_et_MSG);
   if(sel_file_et_file!=NULL)
     {
     strcpy(et_tmp,sel_file_et_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _xsel_file_et_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _write_et_EXEC(NOARG)
{
 if(EntResult)  write_et(); 
  return;
}
LCL VOID CTYP _sel_ifile_et_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL ChrT iet_tmp[65];
LCL VOID CTYP _sel_ifile_et_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP sel_ifile_et_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOff();
  SelParOff();
  sel_ifile_et_file=SelFile(12,19,22,57,BOX_VER,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_BLUE|INTENSE|GREEN,
          1,"*.TEM",_sel_ifile_et_MSG);
   if(sel_ifile_et_file!=NULL)
     {
     strcpy(iet_tmp,sel_ifile_et_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _xsel_ifile_et_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _write_upr_EXEC(NOARG)
{
if(EntResult) write_upr(); 
  return;
}
LCL VOID CTYP _sel_file_upr_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL ChrT upr_tmp[65];
LCL VOID CTYP _sel_file_upr_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP sel_file_upr_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOff();
  SelParOff();
  sel_file_upr_file=SelFile(11,24,22,68,BOX_VER,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_BLUE|INTENSE|GREEN,
          1,"*.UPR",_sel_file_upr_MSG);
   if(sel_file_upr_file!=NULL)
     {
     strcpy(upr_tmp,sel_file_upr_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _xsel_file_upr_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _xsel_file_et_EXEC(NOARG)
{
EdfP e=EctlCur;                        
if(EntResult) {                        
  fnamecpy(FdfBfr(EdfTop),et_tmp);     
  FldInp(); KquePut(Key_C_Home);       
  KquePut(Key_Tab);KquePut(Key_S_Tab); 
  EntResult=0; }                       
  return;
}
LCL VOID CTYP _xsel_ifile_et_EXEC(NOARG)
{
EdfP e=EctlCur;                          
if(EntResult) {                          
  fnamecpy(FdfBfr(EdfTop),iet_tmp);      
  FldInp(); KquePut(Key_C_Home);         
  KquePut(Key_S_Tab); KquePut(Key_Tab);  
  EntResult=0; }                         
  return;
}
LCL VOID CTYP _xsel_file_upr_EXEC(NOARG)
{
EdfP e=EctlCur;                        
if(EntResult) {                        
  fnamecpy(FdfBfr(EdfTop),upr_tmp);    
  FldInp(); KquePut(Key_C_Home);       
  KquePut(Key_Tab);KquePut(Key_S_Tab); 
  EntResult=0; }                       
  return;
}


/*=====================================================================*/


LCL VOID CTYP _help_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("╡ Оперативная помощь ╞",BRD_TOP,19,_GREEN|INTENSE|LGREY);
  return;
}
int main(NOARG)
{
 LCL ChrT _RusUpl[0x100]="ЙйЦцУуКкЕеНнГгШшЩщЗзХхЪъФфЫыВвАаПп"
                         "РрОоЛлДдЖжЭэЯяЧчСсМмИиТтЬьБбЮюЁё";
   TcxlInit();
   TcxlKeyOff();
   NlsUpl=_RusUpl;
 {
 static ChrT ttl[]="";
 int val;
 VposT v;

 VcurGet(v);
 val=HlpDef(HelpFileName,Key_F1,_GREEN|BLACK,_GREEN|INTENSE|LGREY,
        _GREEN|BLACK,HLP_ColorREF,HLP_SelectREF,
        BOX_DBL,_help_MSG);
 switch(val)
    {
    case ERR_NUL:
         HlpTtl(ttl,TTL_CNT,_GREEN|INTENSE|LGREY);
         HlpWind(3,9,22,69,BOX_DBL);
         HlpQutOff();
         break;
    case ERR_MEM:
         Wperror("Мало памяти для инициализации системы помощи");
         break;
    case ERR_ARG:
         Wperror("Файл подсказок не найден");
         break;
    }
 VcurPut(v);
 }
  _startup_EXEC();
 Wopen(0,0,24,79,BOX_SPA,
       _BLACK|BROWN,_BLACK|BROWN);
 CurHide();
  Wprts(24,39,_BLUE|INTENSE|BLUE,"       ║");
  Wprts(24,47,_BLUE|INTENSE|LGREY," ПКЦ \"Системы Триал\" (C) 1995-97 ");
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
 KbndMou(Key_M_ClkL,(VfvCP)SaveCfg,24,0,14);
  Vputn(24,0,"",_BLUE|INTENSE|LGREY,14);
  Vprints(24,1,_BLUE|INTENSE|LGREY,"F2");
  Vprints(24,3,_BLUE|LGREY,"-Сохранить ");
 KbndMou(Key_M_ClkL,(VfvCP)LoadCfg,24,14,13);
  Vputn(24,14,"",_BLUE|INTENSE|LGREY,13);
  Vprints(24,14,_BLUE|INTENSE|LGREY,"F3");
  Vprints(24,16,_BLUE|LGREY,"-Загрузить ");
 KbndMou(Key_M_ClkL,(VfvCP)_shutdown_EXEC,24,27,12);
  Vputn(24,27,"",_BLUE|INTENSE|LGREY,12);
  Vprints(24,27,_BLUE|INTENSE|LGREY,"Alt+X");
  Vprints(24,32,_BLUE|LGREY,"-Выход");
 KbndFre();
 KbndChg(tcxl_old_kb);
   }
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  _do_init_EXEC();
 KbndSet(Key_A_X,(VfvCP)_shutdown_EXEC,0);
 KbndSet(Key_F2,(VfvCP)_savecfg_EXEC,0);
 KbndSet(Key_Esc,(VfvCP)_nil_EXEC,0);
 KbndSet(Key_F3,(VfvCP)_loadcfg_EXEC,0);

 MnuBuild(&_main_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}
   Wclose();
  return 0;
}

/*** END OF FILE ***/
