

/*
 *   Generated by  UI v2.00
 *        November 30, 1995
 */


/* Module: INF_STAT.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif

VOID CTYP _main_2STR(NOARG);

VOID CTYP INF_STAT(NOARG)
{
 Wopen(5,20,15,58,BOX_DBL,
       _RED|INTENSE|BROWN,_RED|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,10,_RED|INTENSE|LGREY,"Идет");
  Wprts(0,15,_RED|INTENSE|LGREY,"эксперимент");
  Wprts(1,8,_RED|LGREY,"╘══════════════════╛");
  Wprts(3,1,_RED|BLACK,"по снятию статических характеристик ");
  Wprts(4,3,_RED|BLACK," прямых и перекрестных каналов    ");
  Wprts(5,3,_RED|BLACK,"      исследуемой системы ");
  Wprts(6,17,_RED|INTENSE|LGREY,"0%");
  Wprts(8,0,_CYAN|BLACK,"     Esc - прервать эксперимент      ");
  return;
}

/*** END OF FILE ***/
