

/*
 *   Generated by  UI v2.00
 *        September 25, 1996
 */


/* Module: INF_GRAF.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif

VOID CTYP _inf_main_2STR(NOARG);

VOID CTYP INF_GRAF(NOARG)
{
 Wopen(6,25,10,49,BOX_VER,
       _GREEN|BLACK,_GREEN|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,5,_GREEN|INTENSE|LGREY,"Идет");
  Wprts(0,10,_GREEN|INTENSE|LGREY,"загрузка");
  Wprts(1,8,_GREEN|INTENSE|LGREY,"модуля");
  Wprts(2,2,_GREEN|INTENSE|LGREY,"просмотра");
  Wprts(2,12,_GREEN|INTENSE|LGREY,"графиков");
  return;
}

/*** END OF FILE ***/
