

/*
 *   Generated by  UI v2.00
 *        January 9, 1997
 */


/* Module: INF_RAB.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif

VOID CTYP _inf_main_2STR(NOARG);

VOID CTYP INF_RAB(NOARG)
{
 Wopen(5,20,16,59,BOX_HOR,
       _RED|INTENSE|BROWN,_RED|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_RGT,10,_RED|INTENSE|BROWN,'│');
  Wprts(0,11,_RED|INTENSE|LGREY,"Идет");
  Wprts(0,16,_RED|INTENSE|LGREY,"эксперимент");
  Wprts(1,9,_RED|LGREY,"╘══════════════════╛ ");
  Wprts(3,4,_RED|LGREY,"Цикл управления    : ");
  Wprts(4,4,_RED|LGREY,"Выполнено в цикле  : ");
  Wprts(5,4,_RED|LGREY,"Пропущено отсчетов : ");
  Wprts(6,4,_RED|LGREY,"Погрешность упр-я  : ");
  Wprts(9,0,_CYAN|BLACK,"       Esc-прервать эксперимент       ");
  return;
}

/*** END OF FILE ***/
