

/*
 *   Generated by  UI v2.00 
 *        April 13, 1995
 */


/* Module: INF_FILE.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif

VOID CTYP _inf_file_main_2STR(NOARG);

VOID CTYP INF_FILE(NOARG)
{
 Wopen(7,26,13,51,BOX_SNG,
       _MAGENTA|INTENSE|LGREY,_MAGENTA|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(1,6,_MAGENTA|INTENSE|LGREY,"ИДЕТ");
  Wprts(1,11,_MAGENTA|INTENSE|LGREY,"ЗАПИСЬ");
  Wprts(3,3,_MAGENTA|INTENSE|LGREY,"ИНФОРМАЦИИ");
  Wprts(3,14,_MAGENTA|INTENSE|LGREY,"В");
  Wprts(3,16,_MAGENTA|INTENSE|LGREY,"ФАЙЛ");
  return;
}

/*** END OF FILE ***/
