

/*
 *   Generated by  UI v2.00
 *        August 16, 1996
 */


/* Module: LOADCFG.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "pro_achh.h"







VOID CTYP _do_EXEC(NOARG);
VOID CTYP _sel_file_SELECT(NOARG);
VOID CTYP _xsel_EXEC(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_OPEN(NOARG);
VOID CTYP _sel_file_2STR(NOARG);
VOID CTYP _sel_file_MSG(NOARG);

LCL ChrT  file[16];

LCL ChrT main_var2[16];
LCL FbldT _main_Fld[]={
 {"",0,0, main_var2,3,6,
  "***************",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _main_Frm={
 _main_Fld,1,NULL,NULL,2,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _main_OPEN(NOARG)
{

 Wopen(8,28,14,56,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " Чтение конфигурации \021" "",BRD_TOP,3,_MAGENTA|INTENSE|GREEN);
  Wmessage("┤                 ├",BRD_BOT,2,_MAGENTA|INTENSE|GREEN);
  Wprts(1,2,_CYAN|BLACK,"Имя");
  Wprts(1,6,_CYAN|BLACK,"файла");
  Wprts(1,12,_CYAN|BLACK,"конфигурации");

  _main_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_main_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _main_2STR(NOARG)
{
  strcpy(main_var2,file); strsetsz(main_var2,15);
 return;
}
LCL VOID CTYP _main_2VAL(NOARG)
{
    strcpy(file,main_var2);
 return;
}

LCL VOID CTYP _do_EXEC(NOARG)
{
if(EntResult)             
   {                      
   xLoadCfg(file);        
   }                      
                          
  return;
}
LCL VOID CTYP _sel_file_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL ChrT sel[65];
LCL VOID CTYP _sel_file_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP sel_file_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOff();
  SelParOff();
  sel_file_file=SelFile(2,47,23,71,BOX_VER,_GREEN|INTENSE|LGREY,_GREEN|BLACK,_LGREY|BLACK,
          0,"*.ini",_sel_file_MSG);
   if(sel_file_file!=NULL)
     {
     strcpy(sel,sel_file_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _xsel_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _xsel_EXEC(NOARG)
{
EdfP e=EctlCur;                          
if(EntResult) {                          
  fnamecpy(FdfBfr(EdfTop),sel);          
  FldInp(); KquePut(Key_C_Home);         
  KquePut(Key_Tab); KquePut(Key_S_Tab);  
  EntResult=0; }                         
  return;
}
VOID CTYP LOADCFG(NOARG)
{
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _main_OPEN();
 KbndSet(Key_F3,_sel_file_SELECT,0);
 KbndMou(Key_M_ClkL,_sel_file_SELECT,14,31,17);
  Vputn(14,31,"",_MAGENTA|INTENSE|GREEN,17);
  Vprints(14,32,_MAGENTA|INTENSE|LGREY,"F3");
  Vprints(14,34,_MAGENTA|INTENSE|GREEN,"-Список");
  Vprints(14,42,_MAGENTA|INTENSE|GREEN,"*.INI");
 _main_2STR();
 if(e) EntPush();
 EntBuild(&_main_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_main_Fld[0].ftag);
 if(val!=ERR_ARG)
    {
    _main_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
  _do_EXEC();
 EntResult=tmp;
}
  return;
}

/*** END OF FILE ***/
