

/*
 *   Generated by  UI v2.00
 *        February 3, 1997
 */


/* Module: POLY_SIN.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* ØÆ´Æ¶•≠®• Æ™≠†    */
         IntT MniC,MniR,MaxC,MaxR;   /* ¢Æß¨Æ¶≠Î• ‡†ß¨•‡Î */
         BytT FrmT;                  /* ‚®Ø °Æ‡§Ó‡†       */
         AtrT FrmA;                  /* †‚‡®°„‚Î °Æ‡§Ó‡†  */
         AtrT Dat;                   /* †‚‡®°„‚Î ‚•™·‚†   */
         BytT Shadow;                /* ‚•≠Ï              */
         AtrT Sat;                   /* Ê¢•‚ ‚•≠®         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "pro_achh.h"

VOID  CTYP _wybor_EXEC(NOARG);
VOID  CTYP _a1_EXEC(NOARG);
VOID  CTYP _a2_EXEC(NOARG);
VOID  CTYP _a3_EXEC(NOARG);
VOID  CTYP _a4_EXEC(NOARG);
VOID CTYP _main_param_2STR(NOARG);
VOID CTYP _main_param_OPEN(NOARG);


LCL ChrT main_param_var1[6];
LCL ChrT main_param_var2[6];
LCL ChrT main_param_var3[6];
LCL ChrT main_param_var4[6];
LCL ChrT main_param_var5[6];
LCL ChrT main_param_var6[6];
LCL ChrT main_param_var7[6];
LCL ChrT main_param_var8[6];
LCL ChrT main_param_var9[6];
LCL ChrT main_param_var10[6];
LCL ChrT main_param_var11[6];
LCL ChrT main_param_var12[6];
LCL ChrT main_param_var13[6];
LCL ChrT main_param_var14[6];
LCL ChrT main_param_var15[6];
LCL ChrT main_param_var16[6];
LCL ChrT main_param_var17[6];
LCL ChrT main_param_var18[6];
LCL ChrT main_param_var19[6];
LCL ChrT main_param_var20[6];
LCL ChrT main_param_var21[6];
LCL ChrT main_param_var22[6];
LCL ChrT main_param_var23[6];
LCL ChrT main_param_var24[6];
LCL ChrT main_param_var25[6];
LCL ChrT main_param_var26[6];
LCL ChrT main_param_var27[6];
LCL ChrT main_param_var28[6];
LCL ChrT main_param_var29[6];
LCL ChrT main_param_var30[6];
LCL ChrT main_param_var31[6];
LCL ChrT main_param_var32[6];
LCL ChrT main_param_var33[6];
LCL ChrT main_param_var34[6];
LCL ChrT main_param_var35[6];
LCL ChrT main_param_var36[6];
LCL ChrT main_param_var37[6];
LCL ChrT main_param_var38[6];
LCL ChrT main_param_var39[6];
LCL ChrT main_param_var40[6];
LCL FbldT _main_param_Fld[]={
 {"",0,0, main_param_var1,2,10,
  "99.99",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var2,2,31,
  "99.99",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var3,2,43,
  "99.99",NULL,NULL,NULL,
  0,3,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var4,2,55,
  "99.99",NULL,NULL,NULL,
  0,4,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var5,3,31,
  "99.99",NULL,NULL,NULL,
  0,5,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var6,3,43,
  "99.99",NULL,NULL,NULL,
  0,6,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var7,3,55,
  "99.99",NULL,NULL,NULL,
  0,7,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var8,4,31,
  "99.99",NULL,NULL,NULL,
  0,8,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var9,4,43,
  "99.99",NULL,NULL,NULL,
  0,9,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var10,4,55,
  "99.99",NULL,NULL,NULL,
  0,10,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var11,6,10,
  "99.99",NULL,NULL,NULL,
  0,11,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var12,6,31,
  "99.99",NULL,NULL,NULL,
  0,12,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var13,6,43,
  "99.99",NULL,NULL,NULL,
  0,13,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var14,6,55,
  "99.99",NULL,NULL,NULL,
  0,14,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var15,7,31,
  "99.99",NULL,NULL,NULL,
  0,15,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var16,7,43,
  "99.99",NULL,NULL,NULL,
  0,16,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var17,7,55,
  "99.99",NULL,NULL,NULL,
  0,17,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var18,8,31,
  "99.99",NULL,NULL,NULL,
  0,18,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var19,8,43,
  "99.99",NULL,NULL,NULL,
  0,19,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var20,8,55,
  "99.99",NULL,NULL,NULL,
  0,20,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var21,10,10,
  "99.99",NULL,NULL,NULL,
  0,21,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var22,10,31,
  "99.99",NULL,NULL,NULL,
  0,22,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var23,10,43,
  "99.99",NULL,NULL,NULL,
  0,23,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var24,10,55,
  "99.99",NULL,NULL,NULL,
  0,24,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var25,11,31,
  "99.99",NULL,NULL,NULL,
  0,25,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var26,11,43,
  "99.99",NULL,NULL,NULL,
  0,26,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var27,11,55,
  "99.99",NULL,NULL,NULL,
  0,27,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var28,12,31,
  "99.99",NULL,NULL,NULL,
  0,28,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var29,12,43,
  "99.99",NULL,NULL,NULL,
  0,29,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var30,12,55,
  "99.99",NULL,NULL,NULL,
  0,30,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var31,14,10,
  "99.99",NULL,NULL,NULL,
  0,31,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var32,14,31,
  "99.99",NULL,NULL,NULL,
  0,32,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var33,14,43,
  "99.99",NULL,NULL,NULL,
  0,33,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var34,14,55,
  "99.99",NULL,NULL,NULL,
  0,34,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var35,15,31,
  "99.99",NULL,NULL,NULL,
  0,35,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var36,15,43,
  "99.99",NULL,NULL,NULL,
  0,36,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var37,15,55,
  "99.99",NULL,NULL,NULL,
  0,37,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var38,16,31,
  "99.99",NULL,NULL,NULL,
  0,38,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var39,16,43,
  "99.99",NULL,NULL,NULL,
  0,39,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var40,16,55,
  "99.99",NULL,NULL,NULL,
  0,40,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _main_param_Frm={
 _main_param_Fld,40,NULL,NULL,41,0|ENT_DIR|ENT_WRP,
 0,_CYAN|BLACK,_LGREY|BLACK,_LGREY|BLACK
};
LCL VOID CTYP _main_param_OPEN(NOARG)
{

 Wopen(5,7,23,71,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,9,_MAGENTA|INTENSE|GREEN,'“');
  Wbprintc(BRD_TOP,17,_MAGENTA|INTENSE|GREEN,'¬');
  Wbprintc(BRD_TOP,28,_MAGENTA|INTENSE|GREEN,'¬');
  Wbprintc(BRD_TOP,40,_MAGENTA|INTENSE|GREEN,'¬');
  Wbprintc(BRD_TOP,52,_MAGENTA|INTENSE|GREEN,'¬');
  Wbprintc(BRD_BOT,3,_MAGENTA|INTENSE|GREEN,'¥');
  Wmessage("Alt+<çÆ¨•‡>-è•‡•©‚® ™ ™†≠†´„, Ctrl+Enter-á†™Æ≠Á®‚Ï",BRD_BOT,4,_MAGENTA|INTENSE|LGREY);
  Wbprintc(BRD_BOT,54,_MAGENTA|INTENSE|GREEN,'√');
  Wbprintc(BRD_LFT,2,_MAGENTA|INTENSE|GREEN,'√');
  Wbprintc(BRD_LFT,6,_MAGENTA|INTENSE|GREEN,'√');
  Wbprintc(BRD_LFT,10,_MAGENTA|INTENSE|GREEN,'√');
  Wbprintc(BRD_LFT,14,_MAGENTA|INTENSE|GREEN,'√');
  Wbprintc(BRD_RGT,2,_MAGENTA|INTENSE|GREEN,'¥');
  Wbprintc(BRD_RGT,6,_MAGENTA|INTENSE|GREEN,'¥');
  Wbprintc(BRD_RGT,10,_MAGENTA|INTENSE|GREEN,'¥');
  Wbprintc(BRD_RGT,14,_MAGENTA|INTENSE|GREEN,'¥');
  Wprts(0,8,_CYAN|BLACK,"∫ë‚†‚®™†≥");
  Wprts(0,18,_CYAN|BLACK,"Ñ®≠†¨®™†");
  Wprts(0,27,_CYAN|BLACK,"≥1");
  Wprts(0,30,_CYAN|BLACK,"£†‡¨Æ≠®™†≥2");
  Wprts(0,42,_CYAN|BLACK,"£†‡¨Æ≠®™†≥3");
  Wprts(0,54,_CYAN|BLACK,"£†‡¨Æ≠®™†");
  Wprts(1,0,_CYAN|BLACK,"ƒƒƒƒƒƒƒƒ◊ƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ");
  Wprts(2,8,_CYAN|BLACK,"∫");
  Wprts(2,15,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(2,16,_CYAN|BLACK,"≥");
  Wprts(2,18,_CYAN|BLACK,"Ä¨Ø´®‚„§†≥");
  Wprts(2,37,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(2,39,_CYAN|BLACK,"≥");
  Wprts(2,49,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(2,51,_CYAN|BLACK,"≥");
  Wprts(2,61,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(3,0,_CYAN|BLACK,"1");
  Wprts(3,2,_CYAN|BLACK,"ä†≠†´");
  Wprts(3,8,_CYAN|BLACK,"∫");
  Wprts(3,16,_CYAN|BLACK,"≥");
  Wprts(3,18,_CYAN|BLACK,"ó†·‚Æ‚†");
  Wprts(3,27,_CYAN|BLACK,"≥");
  Wprts(3,37,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(3,39,_CYAN|BLACK,"≥");
  Wprts(3,49,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(3,51,_CYAN|BLACK,"≥");
  Wprts(3,61,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(4,8,_CYAN|BLACK,"∫");
  Wprts(4,16,_CYAN|BLACK,"≥");
  Wprts(4,18,_CYAN|BLACK,"î†ß†");
  Wprts(4,27,_CYAN|BLACK,"≥");
  Wprts(4,39,_CYAN|BLACK,"≥");
  Wprts(4,51,_CYAN|BLACK,"≥");
  Wprts(5,0,_CYAN|BLACK,"ƒƒƒƒƒƒƒƒ◊ƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ");
  Wprts(6,8,_CYAN|BLACK,"∫");
  Wprts(6,15,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(6,16,_CYAN|BLACK,"≥");
  Wprts(6,18,_CYAN|BLACK,"Ä¨Ø´®‚„§†≥");
  Wprts(6,37,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(6,39,_CYAN|BLACK,"≥");
  Wprts(6,49,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(6,51,_CYAN|BLACK,"≥");
  Wprts(6,61,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(7,0,_CYAN|BLACK,"2");
  Wprts(7,2,_CYAN|BLACK,"ä†≠†´");
  Wprts(7,8,_CYAN|BLACK,"∫");
  Wprts(7,16,_CYAN|BLACK,"≥");
  Wprts(7,18,_CYAN|BLACK,"ó†·‚Æ‚†");
  Wprts(7,27,_CYAN|BLACK,"≥");
  Wprts(7,37,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(7,39,_CYAN|BLACK,"≥");
  Wprts(7,49,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(7,51,_CYAN|BLACK,"≥");
  Wprts(7,61,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(8,8,_CYAN|BLACK,"∫");
  Wprts(8,16,_CYAN|BLACK,"≥");
  Wprts(8,18,_CYAN|BLACK,"î†ß†");
  Wprts(8,27,_CYAN|BLACK,"≥");
  Wprts(8,39,_CYAN|BLACK,"≥");
  Wprts(8,51,_CYAN|BLACK,"≥");
  Wprts(9,0,_CYAN|BLACK,"ƒƒƒƒƒƒƒƒ◊ƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ");
  Wprts(10,8,_CYAN|BLACK,"∫");
  Wprts(10,15,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(10,16,_CYAN|BLACK,"≥");
  Wprts(10,18,_CYAN|BLACK,"Ä¨Ø´®‚„§†≥");
  Wprts(10,37,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(10,39,_CYAN|BLACK,"≥");
  Wprts(10,49,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(10,51,_CYAN|BLACK,"≥");
  Wprts(10,61,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(11,0,_CYAN|BLACK,"3");
  Wprts(11,2,_CYAN|BLACK,"ä†≠†´");
  Wprts(11,8,_CYAN|BLACK,"∫");
  Wprts(11,16,_CYAN|BLACK,"≥");
  Wprts(11,18,_CYAN|BLACK,"ó†·‚Æ‚†");
  Wprts(11,27,_CYAN|BLACK,"≥");
  Wprts(11,37,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(11,39,_CYAN|BLACK,"≥");
  Wprts(11,49,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(11,51,_CYAN|BLACK,"≥");
  Wprts(11,61,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(12,8,_CYAN|BLACK,"∫");
  Wprts(12,16,_CYAN|BLACK,"≥");
  Wprts(12,18,_CYAN|BLACK,"î†ß†");
  Wprts(12,27,_CYAN|BLACK,"≥");
  Wprts(12,39,_CYAN|BLACK,"≥");
  Wprts(12,51,_CYAN|BLACK,"≥");
  Wprts(13,0,_CYAN|BLACK,"ƒƒƒƒƒƒƒƒ◊ƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒ");
  Wprts(14,8,_CYAN|BLACK,"∫");
  Wprts(14,15,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(14,16,_CYAN|BLACK,"≥");
  Wprts(14,18,_CYAN|BLACK,"Ä¨Ø´®‚„§†≥");
  Wprts(14,37,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(14,39,_CYAN|BLACK,"≥");
  Wprts(14,49,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(14,51,_CYAN|BLACK,"≥");
  Wprts(14,61,_CYAN|INTENSE|BLACK,"Ç");
  Wprts(15,0,_CYAN|BLACK,"4");
  Wprts(15,2,_CYAN|BLACK,"ä†≠†´");
  Wprts(15,8,_CYAN|BLACK,"∫");
  Wprts(15,16,_CYAN|BLACK,"≥");
  Wprts(15,18,_CYAN|BLACK,"ó†·‚Æ‚†");
  Wprts(15,27,_CYAN|BLACK,"≥");
  Wprts(15,37,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(15,39,_CYAN|BLACK,"≥");
  Wprts(15,49,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(15,51,_CYAN|BLACK,"≥");
  Wprts(15,61,_CYAN|INTENSE|BLACK,"ÉÊ");
  Wprts(16,8,_CYAN|BLACK,"∫");
  Wprts(16,16,_CYAN|BLACK,"≥");
  Wprts(16,18,_CYAN|BLACK,"î†ß†");
  Wprts(16,27,_CYAN|BLACK,"≥");
  Wprts(16,39,_CYAN|BLACK,"≥");
  Wprts(16,51,_CYAN|BLACK,"≥");

  _main_param_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_main_param_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _main_param_2STR(NOARG)
{
  cvtfc(main_param_var1,Cfg.Def[0].u,5,2);
  cvtfc(main_param_var2,Cfg.Def[0].a[0],5,2);
  cvtfc(main_param_var3,Cfg.Def[0].a[1],5,2);
  cvtfc(main_param_var4,Cfg.Def[0].a[2],5,2);
  cvtfc(main_param_var5,Cfg.Def[0].f[0],5,2);
  cvtfc(main_param_var6,Cfg.Def[0].f[1],5,2);
  cvtfc(main_param_var7,Cfg.Def[0].f[2],5,2);
  cvtfc(main_param_var8,Cfg.Def[0].fa[0],5,2);
  cvtfc(main_param_var9,Cfg.Def[0].fa[1],5,2);
  cvtfc(main_param_var10,Cfg.Def[0].fa[2],5,2);
  cvtfc(main_param_var11,Cfg.Def[1].u,5,2);
  cvtfc(main_param_var12,Cfg.Def[1].a[0],5,2);
  cvtfc(main_param_var13,Cfg.Def[1].a[1],5,2);
  cvtfc(main_param_var14,Cfg.Def[1].a[2],5,2);
  cvtfc(main_param_var15,Cfg.Def[1].f[0],5,2);
  cvtfc(main_param_var16,Cfg.Def[1].f[1],5,2);
  cvtfc(main_param_var17,Cfg.Def[1].f[2],5,2);
  cvtfc(main_param_var18,Cfg.Def[1].fa[0],5,2);
  cvtfc(main_param_var19,Cfg.Def[1].fa[1],5,2);
  cvtfc(main_param_var20,Cfg.Def[1].fa[2],5,2);
  cvtfc(main_param_var21,Cfg.Def[2].u,5,2);
  cvtfc(main_param_var22,Cfg.Def[2].a[0],5,2);
  cvtfc(main_param_var23,Cfg.Def[2].a[1],5,2);
  cvtfc(main_param_var24,Cfg.Def[2].a[2],5,2);
  cvtfc(main_param_var25,Cfg.Def[2].f[0],5,2);
  cvtfc(main_param_var26,Cfg.Def[2].f[1],5,2);
  cvtfc(main_param_var27,Cfg.Def[2].f[2],5,2);
  cvtfc(main_param_var28,Cfg.Def[2].fa[0],5,2);
  cvtfc(main_param_var29,Cfg.Def[2].fa[1],5,2);
  cvtfc(main_param_var30,Cfg.Def[2].fa[2],5,2);
  cvtfc(main_param_var31,Cfg.Def[3].u,5,2);
  cvtfc(main_param_var32,Cfg.Def[3].a[0],5,2);
  cvtfc(main_param_var33,Cfg.Def[3].a[1],5,2);
  cvtfc(main_param_var34,Cfg.Def[3].a[2],5,2);
  cvtfc(main_param_var35,Cfg.Def[3].f[0],5,2);
  cvtfc(main_param_var36,Cfg.Def[3].f[1],5,2);
  cvtfc(main_param_var37,Cfg.Def[3].f[2],5,2);
  cvtfc(main_param_var38,Cfg.Def[3].fa[0],5,2);
  cvtfc(main_param_var39,Cfg.Def[3].fa[1],5,2);
  cvtfc(main_param_var40,Cfg.Def[3].fa[2],5,2);
 return;
}
LCL VOID CTYP _main_param_2VAL(NOARG)
{
    Cfg.Def[0].u=cvtcf(main_param_var1);
    Cfg.Def[0].a[0]=cvtcf(main_param_var2);
    Cfg.Def[0].a[1]=cvtcf(main_param_var3);
    Cfg.Def[0].a[2]=cvtcf(main_param_var4);
    Cfg.Def[0].f[0]=cvtcf(main_param_var5);
    Cfg.Def[0].f[1]=cvtcf(main_param_var6);
    Cfg.Def[0].f[2]=cvtcf(main_param_var7);
    Cfg.Def[0].fa[0]=cvtcf(main_param_var8);
    Cfg.Def[0].fa[1]=cvtcf(main_param_var9);
    Cfg.Def[0].fa[2]=cvtcf(main_param_var10);
    Cfg.Def[1].u=cvtcf(main_param_var11);
    Cfg.Def[1].a[0]=cvtcf(main_param_var12);
    Cfg.Def[1].a[1]=cvtcf(main_param_var13);
    Cfg.Def[1].a[2]=cvtcf(main_param_var14);
    Cfg.Def[1].f[0]=cvtcf(main_param_var15);
    Cfg.Def[1].f[1]=cvtcf(main_param_var16);
    Cfg.Def[1].f[2]=cvtcf(main_param_var17);
    Cfg.Def[1].fa[0]=cvtcf(main_param_var18);
    Cfg.Def[1].fa[1]=cvtcf(main_param_var19);
    Cfg.Def[1].fa[2]=cvtcf(main_param_var20);
    Cfg.Def[2].u=cvtcf(main_param_var21);
    Cfg.Def[2].a[0]=cvtcf(main_param_var22);
    Cfg.Def[2].a[1]=cvtcf(main_param_var23);
    Cfg.Def[2].a[2]=cvtcf(main_param_var24);
    Cfg.Def[2].f[0]=cvtcf(main_param_var25);
    Cfg.Def[2].f[1]=cvtcf(main_param_var26);
    Cfg.Def[2].f[2]=cvtcf(main_param_var27);
    Cfg.Def[2].fa[0]=cvtcf(main_param_var28);
    Cfg.Def[2].fa[1]=cvtcf(main_param_var29);
    Cfg.Def[2].fa[2]=cvtcf(main_param_var30);
    Cfg.Def[3].u=cvtcf(main_param_var31);
    Cfg.Def[3].a[0]=cvtcf(main_param_var32);
    Cfg.Def[3].a[1]=cvtcf(main_param_var33);
    Cfg.Def[3].a[2]=cvtcf(main_param_var34);
    Cfg.Def[3].f[0]=cvtcf(main_param_var35);
    Cfg.Def[3].f[1]=cvtcf(main_param_var36);
    Cfg.Def[3].f[2]=cvtcf(main_param_var37);
    Cfg.Def[3].fa[0]=cvtcf(main_param_var38);
    Cfg.Def[3].fa[1]=cvtcf(main_param_var39);
    Cfg.Def[3].fa[2]=cvtcf(main_param_var40);
 return;
}

LCL VOID CTYP _wybor_EXEC(NOARG)
{
if(EntResult) {          
   Cfg.Def[0].tplCod=1;  
   SetCheck(MctlTag);    
   }                     
  return;
}
LCL VOID CTYP _a1_EXEC(NOARG)
{
                                                
  KquePut(Key_C_Home);                          
  return;
}
LCL VOID CTYP _a2_EXEC(NOARG)
{
int i;                                          
  KquePut(Key_C_Home);                          
  for(i=0;i<10;i++) KquePut(Key_Tab);           
                                                
  return;
}
LCL VOID CTYP _a3_EXEC(NOARG)
{
int i;                                          
  KquePut(Key_C_Home);                          
  for(i=0;i<20;i++) KquePut(Key_Tab);           
                                                
  return;
}
LCL VOID CTYP _a4_EXEC(NOARG)
{
int i;                                          
  KquePut(Key_C_End);                           
  for(i=0;i<9;i++) KquePut(Key_S_Tab);          
                                                
  return;
}
VOID CTYP POLY_SIN(NOARG)
{
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _main_param_OPEN();
 KbndSet(Key_A_1,(VfvCP)_a1_EXEC,0);
 KbndSet(Key_A_2,(VfvCP)_a2_EXEC,0);
 KbndSet(Key_A_3,(VfvCP)_a3_EXEC,0);
 KbndSet(Key_A_4,(VfvCP)_a4_EXEC,0);
 _main_param_2STR();
 if(e) EntPush();
 EntBuild(&_main_param_Frm);
 CurShow();
 val=EntGet(_main_param_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _main_param_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
  _wybor_EXEC();
 EntResult=tmp;
}
  return;
}

/*** END OF FILE ***/
