

/*
 *   Generated by  UI v2.00
 *        February 3, 1997
 */


/* Module: SYS_WZST.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "examine.h"

VOID  CTYP _ish_d_ENTRY(NOARG);
VOID  CTYP _file_wzs_ENTRY(NOARG);
VOID  CTYP _write_wzs_EXEC(NOARG);
VOID  CTYP _sel_file_wz_SELECT(NOARG);
VOID  CTYP _xsel_file_wz_EXEC(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);
VOID CTYP _ish_d_2STR(NOARG);
VOID CTYP _ish_d_OPEN(NOARG);
VOID CTYP _file_wzs_2STR(NOARG);
VOID CTYP _file_wzs_OPEN(NOARG);
VOID CTYP _sel_file_wz_2STR(NOARG);
VOID CTYP _sel_file_wz_MSG(NOARG);


LCL VOID CTYP _opt2_ACT(NOARG)
{
doExamine(exmWZST);
return;
}

LCL VOID CTYP _opt3_ACT(NOARG)
{
graphExamine(exmWZST);
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
tablExamine(exmWZST);
return;
}

LCL IbldT _main_Itm[]={
{"      Исходные данные       ",'\0',ITM_NOR,1,2,  1,HLP_NONE,
   0,2,NULL,_ish_d_ENTRY,NULL,
   NULL,NULL},
{"    Снятие характеристик    ",'\0',ITM_NOR,2,2,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   NULL,NULL},
{"     Просмотр графиков      ",'\0',ITM_NOR,4,2,  5,HLP_NONE,
   0,6,NULL,_opt3_ACT,NULL,
   NULL,NULL},
{" Коэффициенты взаимовлияния ",'\0',ITM_NOR,5,2,  7,HLP_NONE,
   0,8,NULL,_opt4_ACT,NULL,
   NULL,NULL},
{"Запись коэффициентов в файл ",'\0',ITM_NOR,6,2,  9,HLP_NONE,
   0,10,NULL,_file_wzs_ENTRY,NULL,
   NULL,NULL},
};


LCL VOID CTYP _main_MSG(NOARG);
LCL MbldT _main_Mnu={
   _main_Itm,5,7,12,16,45,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|BROWN,_BLUE|INTENSE|BROWN,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_main_MSG,11, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _main_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,1,_BLUE|INTENSE|BROWN,"┌────────────────────────────┐");
  Wprts(1,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,30,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,30,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,1,_BLUE|INTENSE|BROWN,"├────────────────────────────┤");
  Wprts(4,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,30,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,30,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,30,_BLUE|INTENSE|BROWN,"│");
  Wprts(7,1,_BLUE|INTENSE|BROWN,"└────────────────────────────┘");
  {
  MnuDsp(&_main_Mnu);
  }
  return;
}

LCL ChrT ish_d_var1[4];
LCL ChrT ish_d_var3[6];
LCL ChrT ish_d_var4[6];
LCL FbldT _ish_d_Fld[]={
 {"",0,0, ish_d_var1,1,31,
  "999",NULL,NULL,NULL,
  0,12,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_var3,2,29,
  "99.99",NULL,NULL,NULL,
  0,13,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_var4,3,29,
  "99.99",NULL,NULL,NULL,
  0,14,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _ish_d_Frm={
 _ish_d_Fld,3,NULL,NULL,15,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _ish_d_OPEN(NOARG)
{

 Wopen(10,22,17,62,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " Исходные данные эксперимента \021" "",BRD_TOP,5,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Длина");
  Wprts(1,7,_CYAN|BLACK,"исследуемого");
  Wprts(1,20,_CYAN|BLACK,"ряда");
  Wprts(1,35,_CYAN|BLACK,"шт");
  Wprts(2,1,_CYAN|BLACK,"Нижняя");
  Wprts(2,8,_CYAN|BLACK,"граница");
  Wprts(2,16,_CYAN|BLACK,"управления");
  Wprts(2,35,_CYAN|BLACK,"В");
  Wprts(3,1,_CYAN|BLACK,"Верхняя");
  Wprts(3,9,_CYAN|BLACK,"граница");
  Wprts(3,17,_CYAN|BLACK,"управления");
  Wprts(3,35,_CYAN|BLACK,"В");

  _ish_d_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_ish_d_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _ish_d_2STR(NOARG)
{
  cvtic(ish_d_var1,Cfg.Wzst[0].Nq,3);
  cvtfc(ish_d_var3,Cfg.Wzst[0].Lo,5,2);
  cvtfc(ish_d_var4,Cfg.Wzst[0].Hi,5,2);
 return;
}
LCL VOID CTYP _ish_d_2VAL(NOARG)
{
    Cfg.Wzst[0].Nq=cvtci(ish_d_var1);
    Cfg.Wzst[0].Lo=cvtcf(ish_d_var3);
    Cfg.Wzst[0].Hi=cvtcf(ish_d_var4);
 return;
}

LCL VOID CTYP _ish_d_ENTRY(NOARG)
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _ish_d_OPEN();
 _ish_d_2STR();
 if(e) EntPush();
 EntBuild(&_ish_d_Frm);
 CurShow();
 val=EntGet(_ish_d_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _ish_d_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}

LCL ChrT file_wzs_var5[13];
LCL FbldT _file_wzs_Fld[]={
 {"",0,0, file_wzs_var5,1,11,
  "************",NULL,NULL,NULL,
  0,16,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _file_wzs_Frm={
 _file_wzs_Fld,1,NULL,NULL,17,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _file_wzs_OPEN(NOARG)
{

 Wopen(14,34,18,59,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤                 ├",BRD_BOT,2,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");

  _file_wzs_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_file_wzs_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _file_wzs_2STR(NOARG)
{
  strcpy(file_wzs_var5,Cfg.wfile_name); strsetsz(file_wzs_var5,12);
 return;
}
LCL VOID CTYP _file_wzs_2VAL(NOARG)
{
    strcpy(Cfg.wfile_name,file_wzs_var5);
 return;
}

LCL VOID CTYP _file_wzs_ENTRY(NOARG)
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _file_wzs_OPEN();
 KbndSet(Key_F3,(VfvCP)_sel_file_wz_SELECT,0);
 KbndMou(Key_M_ClkL,(VfvCP)_sel_file_wz_SELECT,18,37,17);
  Vputn(18,37,"",_MAGENTA|INTENSE|GREEN,17);
  Vprints(18,38,_MAGENTA|INTENSE|LGREY,"F3");
  Vprints(18,40,_MAGENTA|INTENSE|GREEN,"-Список");
  Vprints(18,48,_MAGENTA|INTENSE|GREEN,"*.WZS");
 _file_wzs_2STR();
 if(e) EntPush();
 EntBuild(&_file_wzs_Frm);
 CurShow();
 val=EntGet(_file_wzs_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _file_wzs_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
  _write_wzs_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _write_wzs_EXEC(NOARG)
{
if(EntResult) write_wzs(); 
  return;
}
LCL VOID CTYP _sel_file_wz_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL ChrT wz_tmp[65];
LCL VOID CTYP _sel_file_wz_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP sel_file_wz_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOff();
  SelParOff();
  sel_file_wz_file=SelFile(12,22,22,60,BOX_VER,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_BLUE|INTENSE|GREEN,
          1,"*.WZS",_sel_file_wz_MSG);
   if(sel_file_wz_file!=NULL)
     {
     strcpy(wz_tmp,sel_file_wz_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _xsel_file_wz_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _xsel_file_wz_EXEC(NOARG)
{
 EdfP e=EctlCur;                     
 if(EntResult) {                     
   fnamecpy(FdfBfr(EdfTop),wz_tmp);  
   FldInp(); KquePut(Key_Tab);       
   EntResult=0;                      
   }                                 
                                     
  return;
}
VOID CTYP SYS_WZST(NOARG)
{
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_main_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}
  return;
}

/*** END OF FILE ***/
