

/*
 *   Generated by  UI v2.00
 *        February 3, 1997
 */


/* Module: SYS_ACHH.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "examine.h"

LCL VOID CTYP Nil(NOARG)
{
 return;
}

VOID  CTYP _ish_d_ENTRY(NOARG);
VOID  CTYP _file_st_ENTRY(NOARG);
VOID  CTYP _write_st_EXEC(NOARG);
VOID  CTYP _sel_file_st_SELECT(NOARG);
VOID  CTYP _xsel_file_st_EXEC(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_MSG(NOARG);
VOID CTYP _ish_d_2STR(NOARG);
VOID CTYP _ish_d_OPEN(NOARG);
VOID CTYP _file_st_2STR(NOARG);
VOID CTYP _file_st_OPEN(NOARG);
VOID CTYP _sel_file_st_2STR(NOARG);
VOID CTYP _sel_file_st_MSG(NOARG);


LCL VOID CTYP _opt2_ACT(NOARG)
{
doExamine(exmACHH);
return;
}

LCL VOID CTYP _opt3_ACT(NOARG)
{
graphExamine(exmACHH);
return;
}

LCL IbldT _MAIN_Itm[]={
{"   Исходные данные   ",'\0',ITM_NOR,1,2,  1,HLP_NONE,
   0,2,NULL,_ish_d_ENTRY,NULL,
   NULL,NULL},
{"     Снятие АЧХ      ",'\0',ITM_NOR,2,2,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   NULL,NULL},
{"  Просмотр графиков  ",'\0',ITM_NOR,4,2,  5,HLP_NONE,
   0,6,NULL,_opt3_ACT,NULL,
   NULL,NULL},
{"    Запись в файл    ",'\0',ITM_NOR,5,2,  7,HLP_NONE,
   0,8,NULL,_file_st_ENTRY,NULL,
   NULL,NULL},
};


LCL VOID CTYP _MAIN_MSG(NOARG);
LCL MbldT _MAIN_Mnu={
   _MAIN_Itm,4,7,27,15,53,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|BROWN,_BLUE|INTENSE|BROWN,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_MAIN_MSG,9, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _MAIN_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,1,_BLUE|INTENSE|BROWN,"┌─────────────────────┐");
  Wprts(1,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,1,_BLUE|INTENSE|BROWN,"├─────────────────────┤");
  Wprts(4,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,1,_BLUE|INTENSE|BROWN,"└─────────────────────┘");
  {
  MnuDsp(&_MAIN_Mnu);
  }
  return;
}

LCL ChrT ish_d_var1[4];
LCL ChrT ish_d_var2[8];
LCL ChrT ish_d_var3[8];
LCL ChrT ish_d_var4[4];
LCL ChrT ish_d_var6[6];
LCL ChrT ish_d_var7[6];
LCL FbldT _ish_d_Fld[]={
 {"",0,0, ish_d_var1,1,31,
  "999",NULL,NULL,NULL,
  0,10,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_var2,2,27,
  "9999.99",NULL,NULL,NULL,
  0,11,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_var3,3,27,
  "9999.99",NULL,NULL,NULL,
  0,12,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_var4,4,31,
  "999",NULL,NULL,NULL,
  0,13,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_var6,6,29,
  "99.99",NULL,NULL,NULL,
  0,14,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_var7,7,29,
  "99.99",NULL,NULL,NULL,
  0,15,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _ish_d_Frm={
 _ish_d_Fld,6,NULL,NULL,16,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _ish_d_OPEN(NOARG)
{

 Wopen(10,33,20,73,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " Исходные данные снятия АЧХ \021" "",BRD_TOP,5,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Число");
  Wprts(1,7,_CYAN|BLACK,"значений");
  Wprts(1,16,_CYAN|BLACK,"АЧХ");
  Wprts(1,26,_CYAN|BLACK,":");
  Wprts(1,35,_CYAN|BLACK,"шт");
  Wprts(2,1,_CYAN|BLACK,"Стартовая");
  Wprts(2,11,_CYAN|BLACK,"частота");
  Wprts(2,26,_CYAN|BLACK,":");
  Wprts(2,35,_CYAN|BLACK,"Гц");
  Wprts(3,1,_CYAN|BLACK,"Максимальная");
  Wprts(3,14,_CYAN|BLACK,"частота");
  Wprts(3,26,_CYAN|BLACK,":");
  Wprts(3,35,_CYAN|BLACK,"Гц");
  Wprts(4,1,_CYAN|BLACK,"Число");
  Wprts(4,7,_CYAN|BLACK,"периодов");
  Wprts(4,16,_CYAN|BLACK,"на");
  Wprts(4,19,_CYAN|BLACK,"точку");
  Wprts(4,26,_CYAN|BLACK,":");
  Wprts(4,35,_CYAN|BLACK,"шт");
  Wprts(6,0,_CYAN|INTENSE|BLACK," ");
  Wprts(6,1,_CYAN|BLACK,"Амплитуда");
  Wprts(6,11,_CYAN|BLACK,"синусоиды");
  Wprts(6,26,_CYAN|BLACK,":");
  Wprts(6,35,_CYAN|BLACK,"В");
  Wprts(7,1,_CYAN|BLACK,"Постоянная");
  Wprts(7,12,_CYAN|BLACK,"составляющая");
  Wprts(7,26,_CYAN|BLACK,":");
  Wprts(7,35,_CYAN|BLACK,"В");

  _ish_d_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_ish_d_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _ish_d_2STR(NOARG)
{
  cvtic(ish_d_var1,Cfg.Ach[0].Nq,3);
  cvtfc(ish_d_var2,Cfg.Ach[0].FreqMin,7,2);
  cvtfc(ish_d_var3,Cfg.Ach[0].FreqMax,7,2);
  cvtic(ish_d_var4,Cfg.Ach[0].Periods,3);
  cvtfc(ish_d_var6,Cfg.Ach[0].Ampl,5,2);
  cvtfc(ish_d_var7,Cfg.Ach[0].Const,5,2);
 return;
}
LCL VOID CTYP _ish_d_2VAL(NOARG)
{
    Cfg.Ach[0].Nq=cvtci(ish_d_var1);
    Cfg.Ach[0].FreqMin=cvtcf(ish_d_var2);
    Cfg.Ach[0].FreqMax=cvtcf(ish_d_var3);
    Cfg.Ach[0].Periods=cvtci(ish_d_var4);
    Cfg.Ach[0].Ampl=cvtcf(ish_d_var6);
    Cfg.Ach[0].Const=cvtcf(ish_d_var7);
 return;
}

LCL VOID CTYP _ish_d_ENTRY(NOARG)
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _ish_d_OPEN();
 _ish_d_2STR();
 if(e) EntPush();
 EntBuild(&_ish_d_Frm);
 CurShow();
 val=EntGet(_ish_d_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _ish_d_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}

LCL ChrT file_st_var5[16];
LCL FbldT _file_st_Fld[]={
 {"",0,0, file_st_var5,1,12,
  "***************",NULL,NULL,NULL,
  0,17,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _file_st_Frm={
 _file_st_Fld,1,NULL,NULL,18,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _file_st_OPEN(NOARG)
{

 Wopen(14,36,18,65,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " Запись в файл \021" "",BRD_TOP,6,_MAGENTA|INTENSE|GREEN);
  Wmessage("┤                 ├",BRD_BOT,2,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");

  _file_st_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_file_st_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _file_st_2STR(NOARG)
{
  strcpy(file_st_var5,Cfg.afile_name); strsetsz(file_st_var5,15);
 return;
}
LCL VOID CTYP _file_st_2VAL(NOARG)
{
    strcpy(Cfg.afile_name,file_st_var5);
 return;
}

LCL VOID CTYP _file_st_ENTRY(NOARG)
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _file_st_OPEN();
 KbndSet(Key_F3,(VfvCP)_sel_file_st_SELECT,0);
 KbndMou(Key_M_ClkL,(VfvCP)_sel_file_st_SELECT,18,39,17);
  Vputn(18,39,"",_MAGENTA|INTENSE|GREEN,17);
  Vprints(18,40,_MAGENTA|INTENSE|LGREY,"F3");
  Vprints(18,42,_MAGENTA|INTENSE|GREEN,"-Список");
  Vprints(18,50,_MAGENTA|INTENSE|GREEN,"*.ACH");
 _file_st_2STR();
 if(e) EntPush();
 EntBuild(&_file_st_Frm);
 CurShow();
 val=EntGet(_file_st_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _file_st_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
  _write_st_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _write_st_EXEC(NOARG)
{
if(EntResult) write_achh(); 
                            
  return;
}
LCL VOID CTYP _sel_file_st_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL ChrT st_tmp[65];
LCL VOID CTYP _sel_file_st_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP sel_file_st_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOff();
  SelParOff();
  sel_file_st_file=SelFile(11,31,22,71,BOX_VER,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_BLUE|INTENSE|GREEN,
          1,"*.ACH",_sel_file_st_MSG);
   if(sel_file_st_file!=NULL)
     {
     strcpy(st_tmp,sel_file_st_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _xsel_file_st_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _xsel_file_st_EXEC(NOARG)
{
EdfP e=EctlCur;                          
if(EntResult) {                          
  fnamecpy(FdfBfr(EdfTop),st_tmp);       
  FldInp(); KquePut(Key_C_Home);         
  KquePut(Key_Tab); KquePut(Key_S_Tab);  
  EntResult=0; }                         
  return;
}
VOID CTYP SYS_ACHH(NOARG)
{
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_MAIN_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}
  return;
}

/*** END OF FILE ***/
