

/*
 *   Generated by  UI v2.00
 *        March 2, 1997
 */


/* Module: SYS_HAR.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "pro_achh.h"

VOID CTYP _BufType_2STR(NOARG);
VOID CTYP _BufType_MSG(NOARG);
VOID CTYP _Mistake_2STR(NOARG);
VOID CTYP _Mistake_MSG(NOARG);
VOID CTYP _AftErr_2STR(NOARG);
VOID CTYP _AftErr_MSG(NOARG);
VOID CTYP _BegType_2STR(NOARG);
VOID CTYP _BegType_MSG(NOARG);
VOID CTYP _main_sys_2STR(NOARG);
VOID CTYP _main_sys_OPEN(NOARG);


LCL IbldT _BufType_Itm[]={
{" Только 640Кб ",'\0',ITM_NOR,0,0,  1,HLP_NONE,
   0,2,NULL,NULL,NULL,
   NULL,NULL},
{" EMS          ",'\0',ITM_NOR,1,0,  3,HLP_NONE,
   0,4,NULL,NULL,NULL,
   NULL,NULL},
};


LCL VOID CTYP _BufType_MSG(NOARG);
LCL MbldT _BufType_Mnu={
   _BufType_Itm,2,12,26,15,41,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _MAGENTA|INTENSE|GREEN,_CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY,
   _CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   0,_BufType_MSG,5, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _BufType_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  {
  MnuDsp(&_BufType_Mnu);
  }
  return;
}
LCL KeyT CTYP _BufType_MENU(NOARG)
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_BufType_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}

LCL IbldT _Mistake_Itm[]={
{" Ср.квадратическая ",'\0',ITM_NOR,0,0,  6,HLP_NONE,
   0,7,NULL,NULL,NULL,
   NULL,NULL},
{" Мат.ожидание      ",'\0',ITM_NOR,1,0,  8,HLP_NONE,
   0,9,NULL,NULL,NULL,
   NULL,NULL},
};


LCL VOID CTYP _Mistake_MSG(NOARG);
LCL MbldT _Mistake_Mnu={
   _Mistake_Itm,2,14,25,17,45,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _MAGENTA|INTENSE|GREEN,_CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY,
   _CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   0,_Mistake_MSG,10, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _Mistake_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  {
  MnuDsp(&_Mistake_Mnu);
  }
  return;
}
LCL KeyT CTYP _Mistake_MENU(NOARG)
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_Mistake_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}

LCL IbldT _AftErr_Itm[]={
{" Останов всех ",'\0',ITM_NOR,0,0,  11,HLP_NONE,
   0,12,NULL,NULL,NULL,
   NULL,NULL},
{" Останов кан. ",'\0',ITM_NOR,1,0,  13,HLP_NONE,
   0,14,NULL,NULL,NULL,
   NULL,NULL},
{" Рестарт всех ",'\0',ITM_NOR,2,0,  15,HLP_NONE,
   0,16,NULL,NULL,NULL,
   NULL,NULL},
{" Рестарт кан. ",'\0',ITM_NOR,3,0,  17,HLP_NONE,
   0,18,NULL,NULL,NULL,
   NULL,NULL},
};


LCL VOID CTYP _AftErr_MSG(NOARG);
LCL MbldT _AftErr_Mnu={
   _AftErr_Itm,4,14,26,19,41,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _MAGENTA|INTENSE|GREEN,_CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY,
   _CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   0,_AftErr_MSG,19, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _AftErr_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  {
  MnuDsp(&_AftErr_Mnu);
  }
  return;
}
LCL KeyT CTYP _AftErr_MENU(NOARG)
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_AftErr_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}

LCL IbldT _BegType_Itm[]={
{" Синусоида ",'\0',ITM_NOR,0,0,  20,HLP_NONE,
   0,21,NULL,NULL,NULL,
   NULL,NULL},
{" Эталон    ",'\0',ITM_NOR,1,0,  22,HLP_NONE,
   0,23,NULL,NULL,NULL,
   NULL,NULL},
};


LCL VOID CTYP _BegType_MSG(NOARG);
LCL MbldT _BegType_Mnu={
   _BegType_Itm,2,13,62,16,74,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _MAGENTA|INTENSE|GREEN,_CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY,
   _CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   0,_BegType_MSG,24, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _BegType_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  {
  MnuDsp(&_BegType_Mnu);
  }
  return;
}
LCL KeyT CTYP _BegType_MENU(NOARG)
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_BegType_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}

LCL ChrT main_sys_var1[2];
LCL ChrT main_sys_var2[8];
LCL ChrT main_sys_var3[7];
LCL ChrT main_sys_var4[5];
LCL ChrT main_sys_var5[15];
LCL IntT CTYP _main_sys_var5_POPUP(ChrP str)
{
 extern MbldT _BufType_Mnu;
 KeyT CTYP _BufType_MENU(NOARG);

   EntPopUpMenu(_BufType_MENU,&_BufType_Mnu);
   return 0;
}
LCL ChrT main_sys_var6[16];
LCL IntT CTYP _main_sys_var6_POPUP(ChrP str)
{
 extern MbldT _Mistake_Mnu;
 KeyT CTYP _Mistake_MENU(NOARG);

   EntPopUpMenu(_Mistake_MENU,&_Mistake_Mnu);
   return 0;
}
LCL ChrT main_sys_var7[8];
LCL ChrT main_sys_var8[8];
LCL ChrT main_sys_var9[8];
LCL ChrT main_sys_var10[8];
LCL ChrT main_sys_var11[15];
LCL IntT CTYP _main_sys_var11_POPUP(ChrP str)
{
 extern MbldT _AftErr_Mnu;
 KeyT CTYP _AftErr_MENU(NOARG);

   EntPopUpMenu(_AftErr_MENU,&_AftErr_Mnu);
   return 0;
}
LCL ChrT main_sys_var12[4];
LCL ChrT main_sys_var13[7];
LCL ChrT main_sys_var14[7];
LCL ChrT main_sys_var17[12];
LCL IntT CTYP _main_sys_var17_POPUP(ChrP str)
{
 extern MbldT _BegType_Mnu;
 KeyT CTYP _BegType_MENU(NOARG);

   EntPopUpMenu(_BegType_MENU,&_BegType_Mnu);
   return 0;
}
LCL ChrT main_sys_var18[7];
LCL ChrT main_sys_var20[7];
LCL ChrT main_sys_var21[7];
LCL ChrT main_sys_var22[6];
LCL ChrT main_sys_var23[6];
LCL ChrT main_sys_var24[7];
LCL ChrT main_sys_var25[3];
LCL ChrT main_sys_var26[16];
LCL FbldT _main_sys_Fld[]={
 {"",0,0, main_sys_var1,1,32,
  "9",NULL,NULL,NULL,
  0,25,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var2,2,26,
  "9999.99",NULL,NULL,NULL,
  0,26,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var3,3,27,
  "999999",NULL,NULL,NULL,
  0,27,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var4,4,29,
  "9999",NULL,NULL,NULL,
  0,28,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var5,5,24,
  "< >*************",NULL,_main_sys_var5_POPUP,NULL,
  0,29,HLP_NONE,
  FLD_NUL|FLD_DEC,2,FLD_CHG},
 {"",0,0, main_sys_var6,8,23,
  "< >**************",NULL,_main_sys_var6_POPUP,NULL,
  0,30,HLP_NONE,
  FLD_NUL|FLD_DEC,2,FLD_CHG},
 {"",0,0, main_sys_var7,9,26,
  "9999.99",NULL,NULL,NULL,
  0,31,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var8,10,26,
  "99999.9",NULL,NULL,NULL,
  0,32,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var9,11,26,
  "99999.9",NULL,NULL,NULL,
  0,33,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var10,12,26,
  "9999.99",NULL,NULL,NULL,
  0,34,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var11,13,24,
  "< >*************",NULL,_main_sys_var11_POPUP,NULL,
  0,35,HLP_NONE,
  FLD_NUL|FLD_DEC,2,FLD_CHG},
 {"",0,0, main_sys_var12,1,66,
  "999",NULL,NULL,NULL,
  0,36,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var13,2,63,
  "99.999",NULL,NULL,NULL,
  0,37,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var14,3,63,
  "99.999",NULL,NULL,NULL,
  0,38,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var17,6,63,
  "< >**********",NULL,_main_sys_var17_POPUP,NULL,
  0,39,HLP_NONE,
  FLD_NUL|FLD_DEC,2,FLD_CHG},
 {"",0,0, main_sys_var18,7,64,
  "9.9999",NULL,NULL,NULL,
  0,40,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var20,8,64,
  "999.99",NULL,NULL,NULL,
  0,41,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var21,9,64,
  "9.9999",NULL,NULL,NULL,
  0,42,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var22,12,64,
  "99999",NULL,NULL,NULL,
  0,43,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var23,13,64,
  "99999",NULL,NULL,NULL,
  0,44,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var24,14,63,
  "999999",NULL,NULL,NULL,
  0,45,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var25,15,67,
  "99",NULL,NULL,NULL,
  0,46,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_sys_var26,15,21,
  "***************",NULL,NULL,NULL,
  0,47,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _main_sys_Frm={
 _main_sys_Fld,23,EntSelect,NULL,48,0|ENT_WRP,
 0,_CYAN|INTENSE|LGREY,_BLUE|INTENSE|BROWN,_BLUE|INTENSE|BROWN
};
LCL VOID CTYP _main_sys_OPEN(NOARG)
{

 Wopen(5,2,23,77,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " ",BRD_TOP,27,_MAGENTA|INTENSE|GREEN);
  Wmessage("Параметры системы",BRD_TOP,29,_MAGENTA|INTENSE|LGREY);
  Wmessage(" \021" "",BRD_TOP,46,_MAGENTA|INTENSE|GREEN);
  Wprts(0,0,_CYAN|INTENSE|GREEN,"   Контур управления   ");
  Wprts(0,23,_CYAN|BLACK,"                ");
  Wprts(0,39,_CYAN|INTENSE|GREEN,"   Запуск эксперимента             ");
  Wprts(1,0,_CYAN|INTENSE|GREEN," ");
  Wprts(1,1,_CYAN|BLACK,"Число каналов управления:");
  Wprts(1,34,_CYAN|BLACK,"шт");
  Wprts(1,36,_CYAN|INTENSE|GREEN," ");
  Wprts(1,38,_CYAN|BLACK,"│ Длительность процесса :");
  Wprts(1,70,_CYAN|BLACK,"сек");
  Wprts(2,1,_CYAN|BLACK,"Частота дискретизации   :");
  Wprts(2,34,_CYAN|BLACK,"Гц");
  Wprts(2,38,_CYAN|BLACK,"│ Уровень покоя         :");
  Wprts(2,70,_CYAN|BLACK,"B");
  Wprts(3,1,_CYAN|BLACK,"Длина ряда              :");
  Wprts(3,34,_CYAN|BLACK,"шт");
  Wprts(3,38,_CYAN|BLACK,"│ Стартовый уровень     :");
  Wprts(3,70,_CYAN|BLACK,"B");
  Wprts(4,1,_CYAN|BLACK,"Число циклов повторения :");
  Wprts(4,34,_CYAN|BLACK,"шт");
  Wprts(4,38,_CYAN|BLACK,"├──────────────────────────────────");
  Wprts(5,1,_CYAN|BLACK,"Размещение эталона    :");
  Wprts(5,38,_CYAN|BLACK,"│");
  Wprts(5,42,_CYAN|INTENSE|GREEN,"Переходный процесс            ");
  Wprts(6,1,_CYAN|BLACK,"─────────────────────────────────────┤ Способ формирования   :");
  Wprts(6,63,_CYAN|INTENSE|LGREY,"Cинусоида");
  Wprts(7,0,_CYAN|INTENSE|GREEN," ");
  Wprts(7,1,_CYAN|BLACK," ");
  Wprts(7,2,_CYAN|INTENSE|GREEN," Механизм защиты                    ");
  Wprts(7,38,_CYAN|BLACK,"│");
  Wprts(7,40,_CYAN|BLACK," Амплитуда управления  :");
  Wprts(7,71,_CYAN|BLACK,"В");
  Wprts(8,1,_CYAN|BLACK,"Расчет погрешности   :");
  Wprts(8,38,_CYAN|BLACK,"│  Частота динамики      :");
  Wprts(8,71,_CYAN|BLACK,"Гц");
  Wprts(9,1,_CYAN|BLACK,"Задержка запуска зашиты :");
  Wprts(9,27,_CYAN|INTENSE|LGREY,":");
  Wprts(9,34,_CYAN|BLACK,"сек │  Коэффициент передачи  :");
  Wprts(9,72,_CYAN|BLACK," ");
  Wprts(10,1,_CYAN|BLACK,"Ограничение по скорости :");
  Wprts(10,34,_CYAN|BLACK,"В/с ├──────────────────────────────────");
  Wprts(11,1,_CYAN|BLACK,"Ограничение по ускорению:");
  Wprts(11,34,_CYAN|BLACK,"В/с¤│");
  Wprts(11,42,_CYAN|INTENSE|GREEN,"Протоколирование работы ");
  Wprts(11,70,_CYAN|BLACK," ");
  Wprts(11,73,_CYAN|BLACK," ");
  Wprts(12,1,_CYAN|BLACK,"Время аварийной работы  :");
  Wprts(12,34,_CYAN|BLACK,"сек │ Детальная информация  :");
  Wprts(12,70,_CYAN|BLACK,"шт  ");
  Wprts(13,0,_CYAN|BLACK," Поставарийные действия:");
  Wprts(13,38,_CYAN|BLACK,"│");
  Wprts(13,39,_CYAN|INTENSE|GREEN," ");
  Wprts(13,40,_CYAN|BLACK,"Контрольный период    :");
  Wprts(13,64,_CYAN|INTENSE|LGREY,"─────");
  Wprts(13,70,_CYAN|BLACK,"мин");
  Wprts(14,0,_CYAN|BLACK," ─────────────────────────────────────┤");
  Wprts(14,40,_CYAN|BLACK,"Мах размер протокола  :");
  Wprts(14,70,_CYAN|BLACK,"Kb");
  Wprts(15,1,_CYAN|BLACK,"Отладочная печать :[");
  Wprts(15,36,_CYAN|BLACK,"]");
  Wprts(15,38,_CYAN|BLACK,"│ Детализац. протокола  :");

  _main_sys_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_main_sys_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _main_sys_2STR(NOARG)
{
  cvtic(main_sys_var1,Cfg.nk,1);
  cvtfc(main_sys_var2,Cfg.Freq,7,2);
  cvtfc(main_sys_var3,Cfg.nr,6,0);
  cvtic(main_sys_var4,Cfg.cycle,4);
  {
   int i;
  for(i=0;i<MbldCnt(&_BufType_Mnu);i++)
       IbldStr(&_BufType_Itm[i])[0]=' ';
  strncpy(main_sys_var5,IbldStr(&_BufType_Itm[Cfg.Def[0].isEMS]),14);
  main_sys_var5[14]=0;
  IbldStr(&_BufType_Itm[Cfg.Def[0].isEMS])[0]='\xFB';
  MbldTag(&_BufType_Mnu)=IbldTag(&_BufType_Itm[Cfg.Def[0].isEMS]);
  }
  {
   int i;
  for(i=0;i<MbldCnt(&_Mistake_Mnu);i++)
       IbldStr(&_Mistake_Itm[i])[0]=' ';
  strncpy(main_sys_var6,IbldStr(&_Mistake_Itm[Cfg.Def[0].mstCod]),15);
  main_sys_var6[15]=0;
  IbldStr(&_Mistake_Itm[Cfg.Def[0].mstCod])[0]='\xFB';
  MbldTag(&_Mistake_Mnu)=IbldTag(&_Mistake_Itm[Cfg.Def[0].mstCod]);
  }
  cvtfc(main_sys_var7,Cfg.Def[0].mstMargin,7,2);
  cvtfc(main_sys_var8,Cfg.Def[0].MaxSpeed,7,1);
  cvtfc(main_sys_var9,Cfg.Def[0].MaxAcceleration,7,1);
  cvtfc(main_sys_var10,Cfg.Def[0].mstTime,7,2);
  {
   int i;
  for(i=0;i<MbldCnt(&_AftErr_Mnu);i++)
       IbldStr(&_AftErr_Itm[i])[0]=' ';
  strncpy(main_sys_var11,IbldStr(&_AftErr_Itm[Cfg.AftErr]),14);
  main_sys_var11[14]=0;
  IbldStr(&_AftErr_Itm[Cfg.AftErr])[0]='\xFB';
  MbldTag(&_AftErr_Mnu)=IbldTag(&_AftErr_Itm[Cfg.AftErr]);
  }
  cvtic(main_sys_var12,Cfg.iniTime,3);
  cvtfc(main_sys_var13,Cfg.Def[0].PassiveVol,6,3);
  cvtfc(main_sys_var14,Cfg.Def[0].StartVol,6,3);
  {
   int i;
  for(i=0;i<MbldCnt(&_BegType_Mnu);i++)
       IbldStr(&_BegType_Itm[i])[0]=' ';
  strncpy(main_sys_var17,IbldStr(&_BegType_Itm[Cfg.Def[0].begCod]),11);
  main_sys_var17[11]=0;
  IbldStr(&_BegType_Itm[Cfg.Def[0].begCod])[0]='\xFB';
  MbldTag(&_BegType_Mnu)=IbldTag(&_BegType_Itm[Cfg.Def[0].begCod]);
  }
  cvtfc(main_sys_var18,Cfg.Def[0].begAmpl,6,4);
  cvtfc(main_sys_var20,Cfg.Def[0].begFreq,6,2);
  cvtfc(main_sys_var21,Cfg.Def[0].begZoom,6,4);
  cvtic(main_sys_var22,Cfg.nr_view,5);
  cvtic(main_sys_var23,Cfg.LogTime,5);
  cvtfc(main_sys_var24,Cfg.LogSize,6,0);
  cvtic(main_sys_var25,Cfg.LogLevel,2);
  strcpy(main_sys_var26,Cfg.DebugLevel); strsetsz(main_sys_var26,15);
 return;
}
LCL VOID CTYP _main_sys_2VAL(NOARG)
{
    Cfg.nk=cvtci(main_sys_var1);
    Cfg.Freq=cvtcf(main_sys_var2);
    Cfg.nr=cvtcf(main_sys_var3);
    Cfg.cycle=cvtci(main_sys_var4);
  {
  int i;
  main_sys_var5[0]='\xFB';
  for(i=0;i<MbldCnt(&_BufType_Mnu);i++)
    if(!strncmp(IbldStr(&_BufType_Itm[i]),main_sys_var5,14))
         {
         Cfg.Def[0].isEMS=i;
         break;
         }
  }
  {
  int i;
  main_sys_var6[0]='\xFB';
  for(i=0;i<MbldCnt(&_Mistake_Mnu);i++)
    if(!strncmp(IbldStr(&_Mistake_Itm[i]),main_sys_var6,15))
         {
         Cfg.Def[0].mstCod=i;
         break;
         }
  }
    Cfg.Def[0].mstMargin=cvtcf(main_sys_var7);
    Cfg.Def[0].MaxSpeed=cvtcf(main_sys_var8);
    Cfg.Def[0].MaxAcceleration=cvtcf(main_sys_var9);
    Cfg.Def[0].mstTime=cvtcf(main_sys_var10);
  {
  int i;
  main_sys_var11[0]='\xFB';
  for(i=0;i<MbldCnt(&_AftErr_Mnu);i++)
    if(!strncmp(IbldStr(&_AftErr_Itm[i]),main_sys_var11,14))
         {
         Cfg.AftErr=i;
         break;
         }
  }
    Cfg.iniTime=cvtci(main_sys_var12);
    Cfg.Def[0].PassiveVol=cvtcf(main_sys_var13);
    Cfg.Def[0].StartVol=cvtcf(main_sys_var14);
  {
  int i;
  main_sys_var17[0]='\xFB';
  for(i=0;i<MbldCnt(&_BegType_Mnu);i++)
    if(!strncmp(IbldStr(&_BegType_Itm[i]),main_sys_var17,11))
         {
         Cfg.Def[0].begCod=i;
         break;
         }
  }
    Cfg.Def[0].begAmpl=cvtcf(main_sys_var18);
    Cfg.Def[0].begFreq=cvtcf(main_sys_var20);
    Cfg.Def[0].begZoom=cvtcf(main_sys_var21);
    Cfg.nr_view=cvtci(main_sys_var22);
    Cfg.LogTime=cvtci(main_sys_var23);
    Cfg.LogSize=cvtcf(main_sys_var24);
    Cfg.LogLevel=cvtci(main_sys_var25);
    strcpy(Cfg.DebugLevel,main_sys_var26);
 return;
}

VOID CTYP SYS_HAR(NOARG)
{
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _main_sys_OPEN();
 _main_sys_2STR();
 if(e) EntPush();
 EntBuild(&_main_sys_Frm);
 CurShow();
 val=EntGet(_main_sys_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _main_sys_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}
  return;
}

/*** END OF FILE ***/
