

/*
 *   Generated by  UI v2.00
 *        March 3, 1997
 */


/* Module: SYS_TEST.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "examine.h"


KeyT  CTYP _static_mn_MENU(NOARG);
VOID  CTYP _ish_d_static_ENTRY(NOARG);
VOID  CTYP _file_st_ENTRY(NOARG);
VOID  CTYP _write_st_EXEC(NOARG);
VOID  CTYP _sel_file_st_SELECT(NOARG);
VOID  CTYP _xsel_file_st_EXEC(NOARG);
VOID CTYP _mode_2STR(NOARG);
VOID CTYP _mode_MSG(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);
VOID CTYP _static_mn_2STR(NOARG);
VOID CTYP _static_mn_MSG(NOARG);
VOID CTYP _ish_d_static_2STR(NOARG);
VOID CTYP _ish_d_static_OPEN(NOARG);
VOID CTYP _file_st_2STR(NOARG);
VOID CTYP _file_st_OPEN(NOARG);
VOID CTYP _sel_file_st_2STR(NOARG);
VOID CTYP _sel_file_st_MSG(NOARG);


LCL IbldT _mode_Itm[]={
{"  Перемещение  ",'\0',ITM_NOR,0,0,  1,HLP_NONE,
   0,2,NULL,NULL,NULL,
   NULL,NULL},
{"  Скорость     ",'\0',ITM_NOR,1,0,  3,HLP_NONE,
   0,4,NULL,NULL,NULL,
   NULL,NULL},
{"  Ускорение    ",'\0',ITM_NOR,2,0,  5,HLP_NONE,
   0,6,NULL,NULL,NULL,
   NULL,NULL},
};


LCL VOID CTYP _mode_MSG(NOARG);
LCL MbldT _mode_Mnu={
   _mode_Itm,3,12,50,16,66,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_HOR,
   _LGREY|BROWN,_BLUE|INTENSE|BROWN,_BLUE|INTENSE|BROWN,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_mode_MSG,7, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _mode_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  {
  MnuDsp(&_mode_Mnu);
  }
  return;
}
LCL KeyT CTYP _mode_MENU(NOARG)
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_mode_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}

LCL VOID CTYP _opt1_ACT(NOARG)
{
/**/
_static_mn_MENU();
return;
}

LCL VOID CTYP _opt2_ACT(NOARG)
{
SYS_WZST();
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
/**/
return;
}

LCL VOID CTYP _opt6_ACT(NOARG)
{
SYS_ACHH();
return;
}

LCL VOID CTYP _opt7_ACT(NOARG)
{
/**/
return;
}

LCL IbldT _main_Itm[]={
{"    Статические характеристики     ",'\0',ITM_NOR,1,2,  8,HLP_NONE,
   0,9,NULL,_opt1_ACT,NULL,
   NULL,NULL},
{"     Взаимодействие в статике      ",'\0',ITM_NOR,2,2,  10,HLP_NONE,
   0,11,NULL,_opt2_ACT,NULL,
   NULL,NULL},
{"    Динамические характеристики    ",'\0',ITM_NOR|ITM_NSL,4,2,  12,HLP_NONE,
   0,13,NULL,_opt4_ACT,NULL,
   NULL,NULL},
{"Амплитудно-частотные характеристики",'\0',ITM_NOR,5,2,  14,HLP_NONE,
   0,15,NULL,_opt6_ACT,NULL,
   NULL,NULL},
{"     Взаимодействие в динамике     ",'\0',ITM_NOR|ITM_NSL,6,2,  16,HLP_NONE,
   0,17,NULL,_opt7_ACT,NULL,
   NULL,NULL},
};


LCL VOID CTYP _main_MSG(NOARG);
LCL MbldT _main_Mnu={
   _main_Itm,5,4,33,13,73,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_main_MSG,18, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _main_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,1,_BLUE|INTENSE|BROWN,"┌───────────\020" " Статика  \021" "────────────┐");
  Wprts(1,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,1,_BLUE|INTENSE|BROWN,"├───────────\020" " Динамика \021" "────────────┤");
  Wprts(4,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(7,1,_BLUE|INTENSE|BROWN,"└───────────────────────────────────┘");
  {
  MnuDsp(&_main_Mnu);
  }
  return;
}

LCL VOID CTYP _opt5_ACT(NOARG)
{
doExamine(exmSTAT);
return;
}

LCL VOID CTYP _opt8_ACT(NOARG)
{
graphExamine(exmSTAT);
return;
}

LCL IbldT _static_mn_Itm[]={
{"   Исходные данные   ",'\0',ITM_NOR,1,2,  19,HLP_NONE,
   0,20,NULL,_ish_d_static_ENTRY,NULL,
   NULL,NULL},
{"Снятие характеристик ",'\0',ITM_NOR,2,2,  21,HLP_NONE,
   0,22,NULL,_opt5_ACT,NULL,
   NULL,NULL},
{"  Просмотр графиков  ",'\0',ITM_NOR,4,2,  23,HLP_NONE,
   0,24,NULL,_opt8_ACT,NULL,
   NULL,NULL},
{"    Запись в файл    ",'\0',ITM_NOR,5,2,  25,HLP_NONE,
   0,26,NULL,_file_st_ENTRY,NULL,
   NULL,NULL},
};


LCL VOID CTYP _static_mn_MSG(NOARG);
LCL MbldT _static_mn_Mnu={
   _static_mn_Itm,4,7,18,15,44,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|BROWN,_BLUE|INTENSE|BROWN,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_static_mn_MSG,27, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _static_mn_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,1,_BLUE|INTENSE|BROWN,"┌─────────────────────┐");
  Wprts(1,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,1,_BLUE|INTENSE|BROWN,"├─────────────────────┤");
  Wprts(4,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,1,_BLUE|INTENSE|BROWN,"└─────────────────────┘");
  {
  MnuDsp(&_static_mn_Mnu);
  }
  return;
}
LCL KeyT CTYP _static_mn_MENU(NOARG)
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_static_mn_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}

LCL ChrT ish_d_static_var1[14];
LCL IntT CTYP _ish_d_static_var1_POPUP(ChrP str)
{
 extern MbldT _mode_Mnu;
 KeyT CTYP _mode_MENU(NOARG);

   EntPopUpMenu(_mode_MENU,&_mode_Mnu);
   return 0;
}
LCL ChrT ish_d_static_var2[4];
LCL ChrT ish_d_static_var3[6];
LCL ChrT ish_d_static_var6[6];
LCL ChrT ish_d_static_var7[6];
LCL ChrT ish_d_static_var8[8];
LCL ChrT ish_d_static_var9[8];
LCL FbldT _ish_d_static_Fld[]={
 {"",0,0, ish_d_static_var1,1,32,
  "< >************",NULL,_ish_d_static_var1_POPUP,NULL,
  0,28,HLP_NONE,
  FLD_NUL|FLD_DEC,2,FLD_CHG},
 {"",0,0, ish_d_static_var2,2,37,
  "999",NULL,NULL,NULL,
  0,29,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_static_var3,3,35,
  "99.99",NULL,NULL,NULL,
  0,30,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_static_var6,6,35,
  "99.99",NULL,NULL,NULL,
  0,31,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_static_var7,7,35,
  "99.99",NULL,NULL,NULL,
  0,32,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_static_var8,9,33,
  "9999.99",NULL,NULL,NULL,
  0,33,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_static_var9,11,33,
  "9999.99",NULL,NULL,NULL,
  0,34,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _ish_d_static_Frm={
 _ish_d_static_Fld,7,EntSelect,NULL,35,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _ish_d_static_OPEN(NOARG)
{

 Wopen(9,29,23,76,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " Исходные данные статических хар-к \021" "",BRD_TOP,5,_MAGENTA|INTENSE|GREEN);
  Wprts(1,2,_CYAN|BLACK,"Тип");
  Wprts(1,6,_CYAN|BLACK,"управления");
  Wprts(1,31,_CYAN|BLACK,":");
  Wprts(2,2,_CYAN|BLACK,"Число");
  Wprts(2,8,_CYAN|BLACK,"значений");
  Wprts(2,31,_CYAN|BLACK,":");
  Wprts(2,41,_CYAN|BLACK,"шт");
  Wprts(3,2,_CYAN|BLACK,"Переходный");
  Wprts(3,13,_CYAN|BLACK,"процесс");
  Wprts(3,31,_CYAN|BLACK,":");
  Wprts(3,41,_CYAN|BLACK,"сек");
  Wprts(5,2,_CYAN|INTENSE|CYAN,"--//-- по перемещению ");
  Wprts(6,2,_CYAN|BLACK,"Нижняя");
  Wprts(6,10,_CYAN|BLACK,"граница");
  Wprts(6,18,_CYAN|BLACK,"управления");
  Wprts(6,31,_CYAN|BLACK,":");
  Wprts(6,41,_CYAN|BLACK,"В");
  Wprts(7,2,_CYAN|BLACK,"Верхняя");
  Wprts(7,10,_CYAN|BLACK,"граница");
  Wprts(7,18,_CYAN|BLACK,"управления");
  Wprts(7,31,_CYAN|BLACK,":");
  Wprts(7,41,_CYAN|BLACK,"В");
  Wprts(8,2,_CYAN|INTENSE|CYAN,"--//-- по скорости    ");
  Wprts(9,2,_CYAN|BLACK,"Верхняя");
  Wprts(9,10,_CYAN|BLACK,"граница");
  Wprts(9,18,_CYAN|BLACK,"управления");
  Wprts(9,31,_CYAN|BLACK,":");
  Wprts(9,41,_CYAN|BLACK,"В/c");
  Wprts(10,2,_CYAN|INTENSE|CYAN,"--//-- по ускорению  ");
  Wprts(11,2,_CYAN|BLACK,"Верхняя");
  Wprts(11,10,_CYAN|BLACK,"граница");
  Wprts(11,18,_CYAN|BLACK,"управления");
  Wprts(11,31,_CYAN|BLACK,":");
  Wprts(11,41,_CYAN|BLACK,"В/c¤");

  _ish_d_static_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_ish_d_static_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _ish_d_static_2STR(NOARG)
{
  {
   int i;
  for(i=0;i<MbldCnt(&_mode_Mnu);i++)
       IbldStr(&_mode_Itm[i])[0]=' ';
  strncpy(ish_d_static_var1,IbldStr(&_mode_Itm[Cfg.Sth[0].Mode]),13);
  ish_d_static_var1[13]=0;
  IbldStr(&_mode_Itm[Cfg.Sth[0].Mode])[0]='\xFB';
  MbldTag(&_mode_Mnu)=IbldTag(&_mode_Itm[Cfg.Sth[0].Mode]);
  }
  cvtic(ish_d_static_var2,Cfg.Sth[0].Nq,3);
  cvtfc(ish_d_static_var3,Cfg.Sth[0].Wait,5,2);
  cvtfc(ish_d_static_var6,Cfg.Sth[0].Lo,5,2);
  cvtfc(ish_d_static_var7,Cfg.Sth[0].Hi,5,2);
  cvtfc(ish_d_static_var8,Cfg.Sth[0].HiSpeed,7,2);
  cvtfc(ish_d_static_var9,Cfg.Sth[0].HiAcceleration,7,2);
 return;
}
LCL VOID CTYP _ish_d_static_2VAL(NOARG)
{
  {
  int i;
  ish_d_static_var1[0]='\xFB';
  for(i=0;i<MbldCnt(&_mode_Mnu);i++)
    if(!strncmp(IbldStr(&_mode_Itm[i]),ish_d_static_var1,13))
         {
         Cfg.Sth[0].Mode=i;
         break;
         }
  }
    Cfg.Sth[0].Nq=cvtci(ish_d_static_var2);
    Cfg.Sth[0].Wait=cvtcf(ish_d_static_var3);
    Cfg.Sth[0].Lo=cvtcf(ish_d_static_var6);
    Cfg.Sth[0].Hi=cvtcf(ish_d_static_var7);
    Cfg.Sth[0].HiSpeed=cvtcf(ish_d_static_var8);
    Cfg.Sth[0].HiAcceleration=cvtcf(ish_d_static_var9);
 return;
}

LCL VOID CTYP _ish_d_static_ENTRY(NOARG)
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _ish_d_static_OPEN();
 _ish_d_static_2STR();
 if(e) EntPush();
 EntBuild(&_ish_d_static_Frm);
 CurShow();
 val=EntGet(_ish_d_static_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _ish_d_static_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}

LCL ChrT file_st_var5[16];
LCL FbldT _file_st_Fld[]={
 {"",0,0, file_st_var5,1,12,
  "***************",NULL,NULL,NULL,
  0,36,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _file_st_Frm={
 _file_st_Fld,1,NULL,NULL,37,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLUE|INTENSE|GREEN
};
LCL VOID CTYP _file_st_OPEN(NOARG)
{

 Wopen(14,34,18,63,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("\020" " Запись в файл \021" "",BRD_TOP,6,_MAGENTA|INTENSE|GREEN);
  Wmessage("┤                 ├",BRD_BOT,2,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");

  _file_st_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_file_st_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _file_st_2STR(NOARG)
{
  strcpy(file_st_var5,Cfg.sfile_name); strsetsz(file_st_var5,15);
 return;
}
LCL VOID CTYP _file_st_2VAL(NOARG)
{
    strcpy(Cfg.sfile_name,file_st_var5);
 return;
}

LCL VOID CTYP _file_st_ENTRY(NOARG)
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _file_st_OPEN();
 KbndSet(Key_F3,(VfvCP)_sel_file_st_SELECT,0);
 KbndMou(Key_M_ClkL,(VfvCP)_sel_file_st_SELECT,18,37,17);
  Vputn(18,37,"",_MAGENTA|INTENSE|GREEN,17);
  Vprints(18,38,_MAGENTA|INTENSE|LGREY,"F3");
  Vprints(18,40,_MAGENTA|INTENSE|GREEN,"-Список");
  Vprints(18,48,_MAGENTA|INTENSE|GREEN,"*.STH");
 _file_st_2STR();
 if(e) EntPush();
 EntBuild(&_file_st_Frm);
 CurShow();
 val=EntGet(_file_st_Fld[0].ftag);
 EntResult=0;
 if(val!=ERR_ARG)
    {
    _file_st_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
  _write_st_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _write_st_EXEC(NOARG)
{
 if(EntResult) write_st(); 
  return;
}
LCL VOID CTYP _sel_file_st_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL ChrT st_tmp[65];
LCL VOID CTYP _sel_file_st_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP sel_file_st_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOff();
  SelParOff();
  sel_file_st_file=SelFile(11,23,22,63,BOX_VER,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_BLUE|INTENSE|GREEN,
          1,"*.STH",_sel_file_st_MSG);
   if(sel_file_st_file!=NULL)
     {
     strcpy(st_tmp,sel_file_st_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _xsel_file_st_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _xsel_file_st_EXEC(NOARG)
{
EdfP e=EctlCur;                          
if(EntResult) {                          
  fnamecpy(FdfBfr(EdfTop),st_tmp);       
  FldInp(); KquePut(Key_C_Home);         
  KquePut(Key_Tab); KquePut(Key_S_Tab);  
  EntResult=0; }                         
  return;
}
VOID CTYP SYS_TEST(NOARG)
{
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_main_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}
  return;
}

/*** END OF FILE ***/
