

/*
 *   Generated by  UI v2.00
 *        February 25, 1996
 */


/* Module: MGEN_DEF.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "mgen_def.h"

static int Chl;









VOID CTYP _gen_WRITE(NOARG);
VOID CTYP _load_EXEC(NOARG);
VOID CTYP _gen_ENTRY(NOARG);
VOID CTYP _channel_MENU(NOARG);
VOID CTYP _ok_MENU(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _setmark_EXEC(NOARG);
VOID CTYP _prgfile_ENTRY(NOARG);
VOID CTYP _signal_MENU(NOARG);
VOID CTYP _background_2STR(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);
VOID CTYP _gen_2STR(NOARG);
VOID CTYP _gen_OPEN(NOARG);
VOID CTYP _channel_2STR(NOARG);
VOID CTYP _channel_MSG(NOARG);
VOID CTYP _ok_2STR(NOARG);
VOID CTYP _ok_MSG(NOARG);
VOID CTYP _signal_2STR(NOARG);
VOID CTYP _signal_MSG(NOARG);
VOID CTYP _prgfile_2STR(NOARG);
VOID CTYP _prgfile_OPEN(NOARG);


LCL VOID CTYP _opt17_ACT(NOARG)
{
_gen_ENTRY();
_gen_WRITE();
return;
}

LCL VOID CTYP _opt19_ACT(NOARG)
{
SaveCfg();
_ok_MENU();
return;
}

LCL IbldT _main_Itm[]={
{"  Генератор   ",'\0',ITM_NOR,1,2,  1,HLP_NONE,
   0,2,NULL,_opt17_ACT,NULL,
   "",NULL},
{"  Каналы ...  ",'\0',ITM_NOR,1,18,  3,HLP_NONE,
   0,4,NULL,_channel_MENU,NULL,
   "",NULL},
{"  Запомнить   ",'\0',ITM_NOR,1,37,  5,HLP_NONE,
   0,6,NULL,_opt19_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _main_MSG(NOARG);
LCL MbldT _main_Mnu={
   _main_Itm,3,18,13,20,65,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SPA,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_main_MSG,7, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _main_MSG(NOARG)
{

 CurHide();
  Wprts(0,0,_BLUE|INTENSE|LGREY,"┌──");
  Wprts(0,4,_BLUE|INTENSE|LGREY,"Выберите");
  Wprts(0,13,_BLUE|INTENSE|LGREY,"режим");
  Wprts(0,19,_BLUE|INTENSE|LGREY,":");
  Wprts(0,21,_BLUE|INTENSE|LGREY,"───────────────────────────────┐");
  Wprts(1,0,_BLUE|INTENSE|LGREY,"│");
  Wprts(1,52,_BLUE|INTENSE|LGREY,"│");
  Wprts(2,0,_BLUE|INTENSE|LGREY,"└───────────────────────────────────────────────────┘");
  {
  MnuDsp(&_main_Mnu);
  }
  return;
}

LCL ChrT gen_var1[16];
LCL ChrT gen_var2[16];
LCL ChrT gen_var3[16];
LCL ChrT gen_var4[4];
LCL ChrT gen_var5[4];
LCL ChrT gen_var7[6];
LCL ChrT gen_var8[6];
LCL FbldT _gen_Fld[]={
 {"",0,0, gen_var1,2,35,
  "999999999999.99",NULL,NULL,NULL,
  0,8,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, gen_var2,3,35,
  "999999999999999",NULL,NULL,NULL,
  0,9,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, gen_var3,4,35,
  "999999999999999",NULL,NULL,NULL,
  0,10,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, gen_var4,6,42,
  "999",NULL,NULL,NULL,
  0,11,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, gen_var5,7,42,
  "999",NULL,NULL,NULL,
  0,12,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, gen_var7,11,47,
  "99999",NULL,NULL,NULL,
  0,13,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, gen_var8,12,47,
  "99999",NULL,NULL,NULL,
  0,14,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _gen_Frm={
 _gen_Fld,7,NULL,NULL,15,0,
 0,_BLUE|INTENSE|LGREY,_LGREY|BLACK,_LGREY|BLACK
};
LCL VOID CTYP _gen_OPEN(NOARG)
{

 Wopen(4,12,17,66,BOX_SPA,
       _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY);
 CurHide();
  Wprts(0,4,_BLUE|INTENSE|LGREY,"ПАРАМЕТРЫ");
  Wprts(1,2,_BLUE|INTENSE|LGREY,"═════════════");
  Wprts(2,2,_BLUE|LGREY,"Частота генерации сигналов   :");
  Wprts(2,51,_BLUE|LGREY,"Гц ");
  Wprts(3,2,_BLUE|LGREY,"Длительность цикла генерации :");
  Wprts(3,51,_BLUE|LGREY,"шт.");
  Wprts(4,2,_BLUE|LGREY,"Число циклов генерации       :");
  Wprts(4,51,_BLUE|LGREY,"шт.");
  Wprts(6,2,_BLUE|LGREY,"Количество активных каналов генерации :");
  Wprts(6,46,_BLUE|LGREY,"шт.");
  Wprts(7,2,_BLUE|LGREY,"Число отсчетов переходного процесса   :");
  Wprts(7,46,_BLUE|LGREY,"шт.");
  Wprts(9,2,_BLUE|INTENSE|LGREY,"УПРАВЛЯЮЩИЕ");
  Wprts(9,14,_BLUE|INTENSE|LGREY,"СИГНАЛЫ");
  Wprts(10,1,_BLUE|INTENSE|LGREY,"═════════════════════");
  Wprts(11,4,_BLUE|LGREY,"Запускающий уровень сигнала     (0..4096):");
  Wprts(12,4,_BLUE|LGREY,"Останавливающий уровень сигнала (0..4096):");

  _gen_2STR();
  EntPush();
  EntBuild(&_gen_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _gen_2STR(NOARG)
{
  cvtfc(gen_var1,Cfg.Freq,15,2);
  cvtfc(gen_var2,Cfg.Time,15,0);
  cvtfc(gen_var3,Cfg.Cycle,15,0);
  cvtic(gen_var4,Cfg.ActChannel,3);
  cvtic(gen_var5,Cfg.Beg,3);
  cvtic(gen_var7,Cfg.StartVol,5);
  cvtic(gen_var8,Cfg.StopVol,5);
 return;
}
LCL VOID CTYP _gen_2VAL(NOARG)
{
    Cfg.Freq=cvtcf(gen_var1);
    Cfg.Time=cvtcf(gen_var2);
    Cfg.Cycle=cvtcf(gen_var3);
    Cfg.ActChannel=cvtci(gen_var4);
    Cfg.Beg=cvtci(gen_var5);
    Cfg.StartVol=cvtci(gen_var7);
    Cfg.StopVol=cvtci(gen_var8);
 return;
}

LCL VOID CTYP _gen_ENTRY(NOARG)
{
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _gen_OPEN();
 _gen_2STR();
 EntPush();
 EntBuild(&_gen_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_gen_Fld[0].ftag);
 if(val!=ERR_ARG)
    {
    _gen_2VAL();
    EntResult=1;
    }
 CurHide();
 EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}
LCL VOID CTYP _gen_WRITE(NOARG)
{
 _gen_OPEN();
 Wunlink(Whandle());
 return;
}
LCL VOID CTYP _load_EXEC(NOARG)
{
LoadCfg();   
             
  return;
}

LCL VOID CTYP _opt5_ACT(NOARG)
{
Chl=0;
_signal_MENU();
return;
}

LCL VOID CTYP _opt7_ACT(NOARG)
{
Chl=1;
_signal_MENU();
return;
}

LCL VOID CTYP _opt8_ACT(NOARG)
{
Chl=2;
_signal_MENU();
return;
}

LCL VOID CTYP _opt9_ACT(NOARG)
{
Chl=3;
_signal_MENU();
return;
}

LCL VOID CTYP _opt10_ACT(NOARG)
{
Chl=4;
_signal_MENU();
return;
}

LCL VOID CTYP _opt11_ACT(NOARG)
{
Chl=5;
_signal_MENU();
return;
}

LCL VOID CTYP _opt12_ACT(NOARG)
{
Chl=6;
_signal_MENU();
return;
}

LCL VOID CTYP _opt14_ACT(NOARG)
{
Chl=7;
_signal_MENU();
return;
}

LCL VOID CTYP _opt15_ACT(NOARG)
{
Chl=8;
_signal_MENU();
return;
}

LCL IbldT _channel_Itm[]={
{" Канал управления N01 ",'\0',ITM_NOR,0,1,  16,HLP_NONE,
   0,17,NULL,_opt5_ACT,NULL,
   "",NULL},
{" Канал управления N02 ",'\0',ITM_NOR,1,1,  18,HLP_NONE,
   0,19,NULL,_opt7_ACT,NULL,
   "",NULL},
{" Канал управления N03 ",'\0',ITM_NOR,2,1,  20,HLP_NONE,
   0,21,NULL,_opt8_ACT,NULL,
   "",NULL},
{" Канал управления N04 ",'\0',ITM_NOR,3,1,  22,HLP_NONE,
   0,23,NULL,_opt9_ACT,NULL,
   "",NULL},
{" Канал управления N05 ",'\0',ITM_NOR,4,1,  24,HLP_NONE,
   0,25,NULL,_opt10_ACT,NULL,
   "",NULL},
{" Канал управления N06 ",'\0',ITM_NOR,5,1,  26,HLP_NONE,
   0,27,NULL,_opt11_ACT,NULL,
   "",NULL},
{" Канал управления N07 ",'\0',ITM_NOR,6,1,  28,HLP_NONE,
   0,29,NULL,_opt12_ACT,NULL,
   "",NULL},
{" Канал управления N08 ",'\0',ITM_NOR,7,1,  30,HLP_NONE,
   0,31,NULL,_opt14_ACT,NULL,
   "",NULL},
{" Канал управления N09 ",'\0',ITM_NOR,8,1,  32,HLP_NONE,
   0,33,NULL,_opt15_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _channel_MSG(NOARG);
LCL MbldT _channel_Mnu={
   _channel_Itm,9,7,28,18,53,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_DBL,
   _CYAN|BLACK,_CYAN|BLACK,_CYAN|BLACK,
   _CYAN|LGREY,_CYAN|LGREY,_BLUE|LGREY,
   0,_channel_MSG,34, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _channel_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage(" Выберите канал ",BRD_TOP,5,_CYAN|BLACK);
  {
  MnuDsp(&_channel_Mnu);
  }
  return;
}
LCL VOID CTYP _channel_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 MbldTag(&_channel_Mnu)=IbldTag(&_channel_Itm[0]);

 MnuBuild(&_channel_Mnu);
 MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
}

LCL IbldT _ok_Itm[]={
{"          Продолжить           ",'\0',ITM_NOR,4,0,  35,HLP_NONE,
   0,36,NULL,NULL,NULL,
   "",NULL},
};


LCL VOID CTYP _ok_MSG(NOARG);
LCL MbldT _ok_Mnu={
   _ok_Itm,1,10,28,16,60,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_DBL,
   _BROWN|INTENSE|LGREY,_BROWN|LGREY,_BROWN|LGREY,
   _BROWN|BLACK,_BROWN|BLACK,_LGREY|BLACK,
   0,_ok_MSG,37, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _ok_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage(" Внимание ",BRD_TOP,11,_BROWN|INTENSE|LGREY);
  Wprts(0,7,_BROWN|LGREY,"Файл");
  Wprts(0,12,_BROWN|LGREY,"конфигурации");
  Wprts(1,2,_BROWN|LGREY,"мультиканального");
  Wprts(1,19,_BROWN|LGREY,"генератора");
  Wprts(2,8,_BROWN|LGREY,"записан");
  Wprts(2,16,_BROWN|INTENSE|LGREY,"успешно");
  {
  MnuDsp(&_ok_Mnu);
  }
  return;
}
LCL VOID CTYP _ok_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 MbldTag(&_ok_Mnu)=IbldTag(&_ok_Itm[0]);

 MnuBuild(&_ok_Mnu);
 MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
}

LCL VOID CTYP _opt1_ACT(NOARG)
{
Cfg.Channel[Chl].Type=Const;
EntPtr=&Cfg.Channel[Chl];
SetConst();
return;
}

LCL VOID CTYP _opt2_ACT(NOARG)
{
Cfg.Channel[Chl].Type=Sin;
EntPtr=&Cfg.Channel[Chl];
SetSin();
return;
}

LCL VOID CTYP _opt3_ACT(NOARG)
{
Cfg.Channel[Chl].Type=PSin;
EntPtr=&Cfg.Channel[Chl];
SetPSin();
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
Cfg.Channel[Chl].Type=DatFile;
EntPtr=&Cfg.Channel[Chl];
SetFile();
return;
}

LCL VOID CTYP _opt6_ACT(NOARG)
{
Cfg.Channel[Chl].Type=PrgFile;
_prgfile_ENTRY();
return;
}

LCL IbldT _signal_Itm[]={
{" Постоянный уровень       ",'\0',ITM_NOR|ITM_AFT,0,1,  38,HLP_NONE,
   0,39,NULL,_opt1_ACT,NULL,
   "",NULL},
{" Синусоидальный сигнал    ",'\0',ITM_NOR|ITM_AFT,1,1,  40,HLP_NONE,
   0,41,NULL,_opt2_ACT,NULL,
   "",NULL},
{" Полигармонический сигнал ",'\0',ITM_NOR|ITM_AFT,2,1,  42,HLP_NONE,
   0,43,NULL,_opt3_ACT,NULL,
   "",NULL},
{" Из файла данных          ",'\0',ITM_NOR|ITM_AFT,3,1,  44,HLP_NONE,
   0,45,NULL,_opt4_ACT,NULL,
   "",NULL},
{" По программе управления  ",'\0',ITM_NOR|ITM_AFT,4,1,  46,HLP_NONE,
   0,47,NULL,_opt6_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _signal_MSG(NOARG);
LCL MbldT _signal_Mnu={
   _signal_Itm,5,4,12,10,41,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|INTENSE|LGREY,_LGREY|BLACK,_LGREY|BLACK,
   _LGREY|INTENSE|LGREY,_LGREY|INTENSE|LGREY,_BLACK|INTENSE|LGREY,
   0,_signal_MSG,48, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _signal_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("Тип управляющего сигнала",BRD_TOP,3,_LGREY|INTENSE|LGREY);
  {
  MnuDsp(&_signal_Mnu);
  }
  return;
}
LCL VOID CTYP _signal_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  _setmark_EXEC();
 MbldTag(&_signal_Mnu)=IbldTag(&_signal_Itm[0]);

 MnuBuild(&_signal_Mnu);
 MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
}
LCL VOID CTYP _setmark_EXEC(NOARG)
{
 int i;                                           
                                                  
 for(i=0;i<5;i++)                                 
   _signal_Itm[i].istr[0]=' ';                    
 _signal_Itm[Cfg.Channel[Chl].Type].istr[0]='+';  
                                                  
  return;
}

LCL ChrT prgfile_var6[16];
LCL FbldT _prgfile_Fld[]={
 {"",0,0, prgfile_var6,1,22,
  "***************",NULL,NULL,NULL,
  0,49,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _prgfile_Frm={
 _prgfile_Fld,1,NULL,NULL,50,0,
 0,_CYAN|BLACK,_LGREY|BLACK,_LGREY|BLACK
};
LCL VOID CTYP _prgfile_OPEN(NOARG)
{

 Wopen(10,25,14,64,BOX_SNG,
       _CYAN|INTENSE|LGREY,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage(" По программе ",BRD_TOP,13,_CYAN|INTENSE|LGREY);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");
  Wprts(1,11,_CYAN|BLACK,"программы:");

  _prgfile_2STR();
  EntPush();
  EntBuild(&_prgfile_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _prgfile_2STR(NOARG)
{
  strcpy(prgfile_var6,Cfg.Channel[Chl].Dat.PrgFile.Name); strsetsz(prgfile_var6,15);
 return;
}
LCL VOID CTYP _prgfile_2VAL(NOARG)
{
    strcpy(Cfg.Channel[Chl].Dat.PrgFile.Name,prgfile_var6);
 return;
}

LCL VOID CTYP _prgfile_ENTRY(NOARG)
{
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _prgfile_OPEN();
 _prgfile_2STR();
 EntPush();
 EntBuild(&_prgfile_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_prgfile_Fld[0].ftag);
 if(val!=ERR_ARG)
    {
    _prgfile_2VAL();
    EntResult=1;
    }
 CurHide();
 EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}


/*=====================================================================*/


int main(NOARG)
{
 LCL ChrT _RusUpl[0x100]="ЙйЦцУуКкЕеНнГгШшЩщЗзХхЪъФфЫыВвАаПп"
                         "РрОоЛлДдЖжЭэЯяЧчСсМмИиТтЬьБбЮюЁё";
   TcxlInit();
   TcxlKeyOff();
   NlsUpl=_RusUpl;
  _load_EXEC();
 Wopen(3,10,21,68,BOX_DBL,
       _BLUE|INTENSE|BROWN,_BLUE|LGREY);
 CurHide();
  Wmessage(" Мультиканальный генератор ",BRD_TOP,16,_BLUE|INTENSE|BROWN);
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
  _gen_WRITE();
 KbndFre();
 KbndChg(tcxl_old_kb);
   }
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 MbldTag(&_main_Mnu)=IbldTag(&_main_Itm[0]);

 MnuBuild(&_main_Mnu);
 MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
}
   Wclose();
  return 0;
}

/*** END OF FILE ***/
