

/*
 *   Generated by  UI v2.00
 *        February 13, 1996
 */


/* Module: SETFILE.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "mgen_def.h"




VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_OPEN(NOARG);


LCL ChrT main_var1[16];
LCL ChrT main_var2[7];
LCL FbldT _main_Fld[]={
 {"",0,0, main_var1,1,20,
  "***************",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, main_var2,2,20,
  "999999",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _main_Frm={
 _main_Fld,2,NULL,NULL,3,0,
 0,_CYAN|BLACK,_LGREY|BLACK,_LGREY|BLACK
};
LCL VOID CTYP _main_OPEN(NOARG)
{

 Wopen(9,25,14,64,BOX_SNG,
       _CYAN|INTENSE|LGREY,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage(" Из файла данных ",BRD_TOP,11,_CYAN|INTENSE|LGREY);
  Wmessage("┤ F3-Выбрать из списка ├",BRD_BOT,8,_CYAN|INTENSE|LGREY);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");
  Wprts(1,11,_CYAN|BLACK,"данных");
  Wprts(1,18,_CYAN|BLACK,":");
  Wprts(2,1,_CYAN|BLACK,"Разрядность");
  Wprts(2,18,_CYAN|BLACK,":");

  _main_2STR();
  EntPush();
  EntBuild(&_main_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _main_2STR(NOARG)
{
  strcpy(main_var1,EntPtr->Dat.DatFile.Name); strsetsz(main_var1,15);
  cvtfc(main_var2,EntPtr->Dat.DatFile.MaxVol,6,0);
 return;
}
LCL VOID CTYP _main_2VAL(NOARG)
{
    strcpy(EntPtr->Dat.DatFile.Name,main_var1);
    EntPtr->Dat.DatFile.MaxVol=cvtcf(main_var2);
 return;
}

VOID CTYP SETFILE(NOARG)
{
{
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _main_OPEN();
 _main_2STR();
 EntPush();
 EntBuild(&_main_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_main_Fld[0].ftag);
 if(val!=ERR_ARG)
    {
    _main_2VAL();
    EntResult=1;
    }
 CurHide();
 EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}
  return;
}

/*** END OF FILE ***/
