

/*
 *   Generated by  UI v2.00
 *        February 1, 1996
 */


/* Module: SETPSIN.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "mgen_def.h"





VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_OPEN(NOARG);


LCL ChrT main_var1[11];
LCL ChrT main_var2[11];
LCL ChrT main_var3[11];
LCL ChrT main_var4[11];
LCL ChrT main_var5[11];
LCL ChrT main_var6[11];
LCL ChrT main_var7[11];
LCL ChrT main_var8[11];
LCL ChrT main_var9[11];
LCL FbldT _main_Fld[]={
 {"",0,0, main_var1,1,25,
  "9999999.99",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var2,2,25,
  "9999999.99",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var3,3,25,
  "9999999.99",NULL,NULL,NULL,
  0,3,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var4,4,26,
  "9999999.99",NULL,NULL,NULL,
  0,4,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var5,5,26,
  "9999999.99",NULL,NULL,NULL,
  0,5,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var6,6,26,
  "9999999.99",NULL,NULL,NULL,
  0,6,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var7,7,27,
  "9999999.99",NULL,NULL,NULL,
  0,7,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var8,8,27,
  "9999999.99",NULL,NULL,NULL,
  0,8,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var9,9,27,
  "9999999.99",NULL,NULL,NULL,
  0,9,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _main_Frm={
 _main_Fld,9,NULL,NULL,10,0,
 0,_CYAN|BLACK,_LGREY|BLACK,_LGREY|BLACK
};
LCL VOID CTYP _main_OPEN(NOARG)
{

 Wopen(8,25,20,65,BOX_SNG,
       _CYAN|INTENSE|LGREY,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage(" Полигармонический сигнал ",BRD_TOP,7,_CYAN|INTENSE|LGREY);
  Wprts(1,1,_CYAN|BLACK,"Амплитуда");
  Wprts(1,11,_CYAN|BLACK,"гармоники");
  Wprts(1,21,_CYAN|BLACK,"1");
  Wprts(1,23,_CYAN|BLACK,":");
  Wprts(1,35,_BLUE|INTENSE|LGREY," ");
  Wprts(2,1,_CYAN|BLACK,"Частота");
  Wprts(2,9,_CYAN|BLACK,"гармоники");
  Wprts(2,21,_CYAN|BLACK,"1");
  Wprts(2,23,_CYAN|BLACK,":");
  Wprts(2,35,_BLUE|INTENSE|LGREY," ");
  Wprts(3,1,_CYAN|BLACK,"Фаза");
  Wprts(3,6,_CYAN|BLACK,"гармоники");
  Wprts(3,21,_CYAN|BLACK,"1");
  Wprts(3,23,_CYAN|BLACK,":");
  Wprts(3,35,_BLUE|INTENSE|LGREY," ");
  Wprts(4,2,_CYAN|BLACK,"Амплитуда");
  Wprts(4,12,_CYAN|BLACK,"гармоники");
  Wprts(4,22,_CYAN|BLACK,"2");
  Wprts(4,24,_CYAN|BLACK,":");
  Wprts(4,36,_BLUE|INTENSE|LGREY," ");
  Wprts(5,2,_CYAN|BLACK,"Частота");
  Wprts(5,10,_CYAN|BLACK,"гармоники");
  Wprts(5,22,_CYAN|BLACK,"2");
  Wprts(5,24,_CYAN|BLACK,":");
  Wprts(5,36,_BLUE|INTENSE|LGREY," ");
  Wprts(6,2,_CYAN|BLACK,"Фаза");
  Wprts(6,7,_CYAN|BLACK,"гармоники");
  Wprts(6,22,_CYAN|BLACK,"2");
  Wprts(6,24,_CYAN|BLACK,":");
  Wprts(6,36,_BLUE|INTENSE|LGREY," ");
  Wprts(7,3,_CYAN|BLACK,"Амплитуда");
  Wprts(7,13,_CYAN|BLACK,"гармоники");
  Wprts(7,23,_CYAN|BLACK,"3");
  Wprts(7,25,_CYAN|BLACK,":");
  Wprts(7,37,_BLUE|INTENSE|LGREY," ");
  Wprts(8,3,_CYAN|BLACK,"Частота");
  Wprts(8,11,_CYAN|BLACK,"гармоники");
  Wprts(8,23,_CYAN|BLACK,"3");
  Wprts(8,25,_CYAN|BLACK,":");
  Wprts(8,37,_BLUE|INTENSE|LGREY," ");
  Wprts(9,3,_CYAN|BLACK,"Фаза");
  Wprts(9,8,_CYAN|BLACK,"гармоники");
  Wprts(9,23,_CYAN|BLACK,"3");
  Wprts(9,25,_CYAN|BLACK,":");
  Wprts(9,37,_BLUE|INTENSE|LGREY," ");

  _main_2STR();
  EntPush();
  EntBuild(&_main_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _main_2STR(NOARG)
{
  cvtfc(main_var1,EntPtr->Dat.PSin.Ampl[0],10,2);
  cvtfc(main_var2,EntPtr->Dat.PSin.Freq[0],10,2);
  cvtfc(main_var3,EntPtr->Dat.PSin.Faza[0],10,2);
  cvtfc(main_var4,EntPtr->Dat.PSin.Ampl[1],10,2);
  cvtfc(main_var5,EntPtr->Dat.PSin.Freq[1],10,2);
  cvtfc(main_var6,EntPtr->Dat.PSin.Faza[1],10,2);
  cvtfc(main_var7,EntPtr->Dat.PSin.Ampl[2],10,2);
  cvtfc(main_var8,EntPtr->Dat.PSin.Freq[2],10,2);
  cvtfc(main_var9,EntPtr->Dat.PSin.Faza[2],10,2);
 return;
}
LCL VOID CTYP _main_2VAL(NOARG)
{
    EntPtr->Dat.PSin.Ampl[0]=cvtcf(main_var1);
    EntPtr->Dat.PSin.Freq[0]=cvtcf(main_var2);
    EntPtr->Dat.PSin.Faza[0]=cvtcf(main_var3);
    EntPtr->Dat.PSin.Ampl[1]=cvtcf(main_var4);
    EntPtr->Dat.PSin.Freq[1]=cvtcf(main_var5);
    EntPtr->Dat.PSin.Faza[1]=cvtcf(main_var6);
    EntPtr->Dat.PSin.Ampl[2]=cvtcf(main_var7);
    EntPtr->Dat.PSin.Freq[2]=cvtcf(main_var8);
    EntPtr->Dat.PSin.Faza[2]=cvtcf(main_var9);
 return;
}

VOID CTYP SETPSIN(NOARG)
{
{
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _main_OPEN();
 _main_2STR();
 EntPush();
 EntBuild(&_main_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_main_Fld[0].ftag);
 if(val!=ERR_ARG)
    {
    _main_2VAL();
    EntResult=1;
    }
 CurHide();
 EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}
  return;
}

/*** END OF FILE ***/
