

/*
 *   Generated by  UI v2.00
 *        April 17, 1995
 */


/* Module: MNUVIEW.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include  "view.h"

VOID CTYP _title_WRITE(NOARG);
VOID CTYP _sth_SELECT(NOARG);
VOID CTYP _wzs_SELECT(NOARG);
VOID CTYP _tem_SELECT(NOARG);
VOID CTYP _tem_SELECT(NOARG);
VOID CTYP _sth_do_EXEC(NOARG);
VOID CTYP _wzs_do_EXEC(NOARG);
VOID CTYP _tem_do_EXEC(NOARG);
VOID CTYP _background_2STR(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);
VOID CTYP _title_2STR(NOARG);
VOID CTYP _sth_2STR(NOARG);
VOID CTYP _sth_MSG(NOARG);
VOID CTYP _wzs_2STR(NOARG);
VOID CTYP _wzs_MSG(NOARG);
VOID CTYP _tem_2STR(NOARG);
VOID CTYP _tem_MSG(NOARG);


LCL VOID CTYP _opt3_ACT(NOARG)
{
Sel=1;
_tem_SELECT();
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
Sel=2;
_tem_SELECT();
return;
}

LCL IbldT _main_Itm[]={
{" Статические характеристики ",'\0',ITM_NOR,1,1,  1,HLP_NONE,
   0,2,NULL,_sth_SELECT,NULL,
   "",NULL},
{"            АЧХ             ",'\0',ITM_NOR,2,1,  3,HLP_NONE,
   0,4,NULL,_wzs_SELECT,NULL,
   "",NULL},
{"     Формат: вход/выход     ",'\0',ITM_NOR,6,1,  5,HLP_NONE,
   0,6,NULL,_opt3_ACT,NULL,
   "",NULL},
{"    Формат: эталон/выход    ",'\0',ITM_NOR,7,1,  7,HLP_NONE,
   0,8,NULL,_opt4_ACT,NULL,
   "",NULL},
{"      Закончить работу      ",'\0',ITM_NOR,10,1,  9,HLP_NONE,
   0,10,NULL,NULL,NULL,
   "",NULL},
};


LCL VOID CTYP _main_MSG(NOARG);
LCL MbldT _main_Mnu={
   _main_Itm,5,8,24,20,55,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_VER,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_CYAN|INTENSE|LGREY,
   0,_main_MSG,11, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _main_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage(" Характеристики системы ",BRD_TOP,3,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_LFT,5,_BLUE|INTENSE|LGREY,'╟');
  Wbprintc(BRD_LFT,10,_BLUE|INTENSE|LGREY,'╟');
  Wbprintc(BRD_RGT,5,_BLUE|INTENSE|LGREY,'╢');
  Wbprintc(BRD_RGT,10,_BLUE|INTENSE|LGREY,'╢');
  Wprts(4,0,_BLUE|INTENSE|LGREY,"──");
  Wprts(4,3,_BLUE|INTENSE|LGREY,"Результаты");
  Wprts(4,14,_BLUE|INTENSE|LGREY,"управления");
  Wprts(4,25,_BLUE|INTENSE|LGREY,"─────");
  Wprts(6,1,_BLUE|INTENSE|LGREY,"─");
  Wprts(6,3,_BLUE|INTENSE|LGREY,"Эталонные");
  Wprts(6,13,_BLUE|INTENSE|LGREY,"сигналы");
  Wprts(6,21,_BLUE|INTENSE|LGREY,"────────");
  Wprts(9,0,_BLUE|INTENSE|LGREY,"──────────────────────────────");
  {
  MnuDsp(&_main_Mnu);
  }
  return;
}
LCL VOID CTYP _title_WRITE(NOARG)
{
 Wopen(2,14,7,64,BOX_SNG,
       _BROWN|INTENSE|LGREY,_BROWN|INTENSE|LGREY);
 CurHide();
  Wprts(0,20,_BROWN|INTENSE|LGREY,"ПРОСМОТР");
  Wprts(1,6,_BROWN|INTENSE|LGREY,"результатов");
  Wprts(1,18,_BROWN|INTENSE|LGREY,"проведения");
  Wprts(1,29,_BROWN|INTENSE|LGREY,"экспериментов");
  Wprts(2,2,_BROWN|INTENSE|LGREY,"с");
  Wprts(2,4,_BROWN|INTENSE|LGREY,"использованием");
  Wprts(2,19,_BROWN|INTENSE|CYAN,"АДАПТИВНОЙ СИСТЕМЫ УПРАВЛЕНИЯ");
  Wprts(3,15,_BROWN|INTENSE|LGREY,"в");
  Wprts(3,17,_BROWN|INTENSE|LGREY,"графическом");
  Wprts(3,29,_BROWN|INTENSE|LGREY,"виде");
 Wunlink(Whandle());
 return;
}
LCL VOID CTYP _sth_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL VOID CTYP _sth_SELECT(NOARG)
{
 ChrP sth_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 tcxl_old_kb=KbndChg(tcxl_kb);
  EntResult=0;
  sth_file=SelFile(11,27,23,65,BOX_HOR,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_LGREY|BLACK,
          1,"*.STH",_sth_MSG);
   if(sth_file!=NULL)
     {
     strcpy(sth_filename,sth_file);
     SelFree();
     EntResult=1;
     }

 KbndChg(tcxl_old_kb);
  _sth_do_EXEC();
}
LCL VOID CTYP _wzs_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL VOID CTYP _wzs_SELECT(NOARG)
{
 ChrP wzs_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 tcxl_old_kb=KbndChg(tcxl_kb);
  EntResult=0;
  wzs_file=SelFile(11,27,23,65,BOX_HOR,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_LGREY|BLACK,
          1,"*.ACH",_wzs_MSG);
   if(wzs_file!=NULL)
     {
     strcpy(wzs_filename,wzs_file);
     SelFree();
     EntResult=1;
     }

 KbndChg(tcxl_old_kb);
  _wzs_do_EXEC();
}
LCL VOID CTYP _tem_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL VOID CTYP _tem_SELECT(NOARG)
{
 ChrP tem_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 tcxl_old_kb=KbndChg(tcxl_kb);
  EntResult=0;
  tem_file=SelFile(11,27,23,65,BOX_HOR,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_LGREY|BLACK,
          1,"*.UPR",_tem_MSG);
   if(tem_file!=NULL)
     {
     strcpy(tem_filename,tem_file);
     SelFree();
     EntResult=1;
     }

 KbndChg(tcxl_old_kb);
  _tem_do_EXEC();
}
LCL VOID CTYP _sth_do_EXEC(NOARG)
{
if(EntResult) ViewSTH();
  return;
}
LCL VOID CTYP _wzs_do_EXEC(NOARG)
{
if(EntResult) ViewWZS();
  return;
}
LCL VOID CTYP _tem_do_EXEC(NOARG)
{
if(EntResult) ViewTEM();
  return;
}


/*=====================================================================*/


int main(NOARG)
{
 LCL ChrT _RusUpl[0x100]="ЙйЦцУуКкЕеНнГгШшЩщЗзХхЪъФфЫыВвАаПп"
                         "РрОоЛлДдЖжЭэЯяЧчСсМмИиТтЬьБбЮюЁё";
   TcxlInit();
   TcxlKeyOff();
   NlsUpl=_RusUpl;
 Wopen(0,0,24,79,BOX_SPA,
       _CYAN|INTENSE|BLACK,_CYAN|INTENSE|BLACK);
 CurHide();
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
  _title_WRITE();
 KbndChg(tcxl_old_kb);
   }
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_main_Mnu)=IbldTag(&_main_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_main_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
   Wclose();
  return 0;
}

/*** END OF FILE ***/
