

/*
 *   Generated by  UI v2.00
 *        September 10, 1995
 */


/* Module: DSYS.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include <dsysdef.h>

LCL int Chl;

LCL VOID CTYP StubFunc(NOARG)
{ return; }


VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);

LCL VOID CTYP _selarea_MSG(NOARG)
{

 CurHide();
  return;
}
LCL VOID CTYP _main_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage(" Емулятор объекта управления ",BRD_TOP,3,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_LFT,22,_BLUE|INTENSE|LGREY,'╟');
  Wbprintc(BRD_RGT,22,_BLUE|INTENSE|LGREY,'╢');
  Wprts(18,22,_BLUE|LGREY," ");
  Wprts(20,0,_BLUE|BLACK," ");
  Wprts(21,0,_BLUE|INTENSE|LGREY,"──────────────────────────────────────────────────────────────────────────────");
 KrefSet(22,2,23,Key_Ent,ChannelDef,0);
  Vputn(23,3,"",_CYAN|INTENSE|LGREY,23);
  Vprints(23,3,_LGREY|BLACK," ");
  Vprints(23,4,_LGREY|RED,"Enter");
  Vprints(23,9,_LGREY|BLACK,"-Описание канала ");
 KrefSet(22,29,31,Key_C_X,ChennelXref,0);
  Vputn(23,30,"",_BLUE|INTENSE|LGREY,31);
  Vprints(23,30,_LGREY|BLACK,"  ");
  Vprints(23,32,_LGREY|RED,"Ctrl+X");
  Vprints(23,38,_LGREY|BLACK,"-Взаимовлияние каналов ");
 KrefSet(22,65,11,Key_Esc,StubFunc,Key_Esc);
  Vputn(23,66,"",_GREEN|INTENSE|LGREY,11);
  Vprints(23,66,_LGREY|BLACK," ");
  Vprints(23,67,_LGREY|RED,"Esc");
  Vprints(23,70,_LGREY|BLACK,"-Выход ");
  return;
}


/*=====================================================================*/


int main(NOARG)
{
 LCL ChrT _RusUpl[0x100]="ЙйЦцУуКкЕеНнГгШшЩщЗзХхЪъФфЫыВвАаПп"
                         "РрОоЛлДдЖжЭэЯяЧчСсМмИиТтЬьБбЮюЁё";
   TcxlInit();
   TcxlKeyOff();
   NlsUpl=_RusUpl;
{
 IntT tmp=EntResult;
 IntT main_val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
 Wopen(0,0,24,79,BOX_DBL,
       _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY);
 _main_MSG();
  main_val=SelStr(1,1,21,78,BOX_SPA,
             _CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY,_LGREY|BLACK,
             ChannelList,0,_selarea_MSG);
  Wclose();
  if(main_val!=ERR_ARG)
     {
     Chl=main_val;
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
 EntResult=tmp;
}
  return 0;
}

/*** END OF FILE ***/
