/* LabWindows User Interface Resource (UIR) Include File                  */
/* Copyright (c) National Instruments 1992. All Rights Reserved.          */

/* WARNING: Do not add to, delete from, or otherwise modify the contents  */
/*          of this include file.                                         */


#define  VM  0
#define  VM_INPUTS  0
#define  VM_AVERAGE  1
#define  VM_START  2
#define  VM_STOP  3
#define  VM_RESET  4
#define  VM_QUIT  5
