

/*
 *   Generated by  UI v2.00
 *        September 7, 1996
 */


/* Module: TESTPARM.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "upi_3w.h"

extern int Chl;


VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_OPEN(NOARG);


LCL ChrT main_var1[4];
LCL ChrT main_var2[6];
LCL ChrT main_var3[11];
LCL ChrT main_var4[11];
LCL ChrT main_var5[11];
LCL ChrT main_var6[11];
LCL ChrT main_var7[11];
LCL ChrT main_var8[11];
LCL ChrT main_var9[11];
LCL ChrT main_var10[11];
LCL ChrT main_var11[11];
LCL ChrT main_var12[11];
LCL ChrT main_var13[11];
LCL ChrT main_var14[11];
LCL ChrT main_var15[11];
LCL ChrT main_var16[11];
LCL ChrT main_var17[11];
LCL ChrT main_var18[11];
LCL ChrT main_var19[11];
LCL ChrT main_var20[11];
LCL ChrT main_var21[11];
LCL ChrT main_var22[11];
LCL ChrT main_var23[11];
LCL FbldT _main_Fld[]={
 {"",0,0, main_var1,0,20,
  "999",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var2,0,30,
  "9.999",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var3,2,13,
  "9.99999999",NULL,NULL,NULL,
  0,3,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var4,2,25,
  "9.99999999",NULL,NULL,NULL,
  0,4,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var5,3,13,
  "9.99999999",NULL,NULL,NULL,
  0,5,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var6,3,25,
  "9.99999999",NULL,NULL,NULL,
  0,6,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var7,4,13,
  "9.99999999",NULL,NULL,NULL,
  0,7,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var8,4,25,
  "9.99999999",NULL,NULL,NULL,
  0,8,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var9,5,13,
  "9.99999999",NULL,NULL,NULL,
  0,9,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var10,5,25,
  "9.99999999",NULL,NULL,NULL,
  0,10,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var11,6,13,
  "9.99999999",NULL,NULL,NULL,
  0,11,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var12,6,25,
  "9.99999999",NULL,NULL,NULL,
  0,12,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var13,7,13,
  "9.99999999",NULL,NULL,NULL,
  0,13,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var14,9,13,
  "9.99999999",NULL,NULL,NULL,
  0,14,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var15,9,25,
  "9.99999999",NULL,NULL,NULL,
  0,15,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var16,10,13,
  "9.99999999",NULL,NULL,NULL,
  0,16,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var17,10,25,
  "9.99999999",NULL,NULL,NULL,
  0,17,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var18,11,13,
  "9.99999999",NULL,NULL,NULL,
  0,18,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var19,11,25,
  "9.99999999",NULL,NULL,NULL,
  0,19,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var20,12,13,
  "9.99999999",NULL,NULL,NULL,
  0,20,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var21,12,25,
  "9.99999999",NULL,NULL,NULL,
  0,21,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var22,13,13,
  "9.99999999",NULL,NULL,NULL,
  0,22,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var23,13,25,
  "9.99999999",NULL,NULL,NULL,
  0,23,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _main_Frm={
 _main_Fld,23,NULL,NULL,24,0,
 0,_BLUE|INTENSE|GREEN,_LGREY|BLACK,_LGREY|BLACK
};
LCL VOID CTYP _main_OPEN(NOARG)
{

 Wopen(8,12,23,50,BOX_DBL,
       _CYAN|BLACK,_BLUE|INTENSE|GREEN);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,0,_CYAN|BLACK,"  Порядок модели :  ");
  Wprts(0,23,_CYAN|BLACK,",    E=");
  Wprts(0,35,_CYAN|BLACK,"  ");
  Wprts(1,0,_CYAN|BLACK,"                                     ");
  Wprts(2,0,_CYAN|BLACK," C[0..10]=   ");
  Wprts(2,23,_CYAN|BLACK,"  ");
  Wprts(2,35,_CYAN|BLACK,"  ");
  Wprts(3,0,_CYAN|BLACK,"             ");
  Wprts(3,23,_CYAN|BLACK,"  ");
  Wprts(3,35,_CYAN|BLACK,"  ");
  Wprts(4,0,_CYAN|BLACK,"             ");
  Wprts(4,23,_CYAN|BLACK,"  ");
  Wprts(4,35,_CYAN|BLACK,"  ");
  Wprts(5,0,_CYAN|BLACK,"             ");
  Wprts(5,23,_CYAN|BLACK,"  ");
  Wprts(5,35,_CYAN|BLACK,"  ");
  Wprts(6,0,_CYAN|BLACK,"             ");
  Wprts(6,23,_CYAN|BLACK,"  ");
  Wprts(6,35,_CYAN|BLACK,"  ");
  Wprts(7,0,_CYAN|BLACK,"                                     ");
  Wprts(8,0,_CYAN|BLACK,"                                     ");
  Wprts(9,0,_CYAN|BLACK," Lam[1..10]= ");
  Wprts(9,23,_CYAN|BLACK,"  ");
  Wprts(9,35,_CYAN|BLACK,"  ");
  Wprts(10,0,_CYAN|BLACK,"             ");
  Wprts(10,23,_CYAN|BLACK,"  ");
  Wprts(10,35,_CYAN|BLACK,"  ");
  Wprts(11,0,_CYAN|BLACK,"             ");
  Wprts(11,23,_CYAN|BLACK,"  ");
  Wprts(11,35,_CYAN|BLACK,"  ");
  Wprts(12,0,_CYAN|BLACK,"             ");
  Wprts(12,23,_CYAN|BLACK,"  ");
  Wprts(12,35,_CYAN|BLACK,"  ");
  Wprts(13,0,_CYAN|BLACK,"             ");
  Wprts(13,23,_CYAN|BLACK,"  ");
  Wprts(13,35,_CYAN|BLACK,"  ");

  _main_2STR();
  {
  EdfP e=EctlCur;
  if(e) EntPush();
  EntBuild(&_main_Frm);
  EntDsp();
  EntFree();
  if(e) EntPop();
  }

  return;
}
LCL VOID CTYP _main_2STR(NOARG)
{
  cvtic(main_var1,def.Tm[Chl][Z_curr].p,3);
  cvtfc(main_var2,def.Tm[Chl][Z_curr].E,5,3);
  cvtfc(main_var3,def.Tm[Chl][Z_curr].C[0],10,8);
  cvtfc(main_var4,def.Tm[Chl][Z_curr].C[1],10,8);
  cvtfc(main_var5,def.Tm[Chl][Z_curr].C[2],10,8);
  cvtfc(main_var6,def.Tm[Chl][Z_curr].C[3],10,8);
  cvtfc(main_var7,def.Tm[Chl][Z_curr].C[4],10,8);
  cvtfc(main_var8,def.Tm[Chl][Z_curr].C[5],10,8);
  cvtfc(main_var9,def.Tm[Chl][Z_curr].C[6],10,8);
  cvtfc(main_var10,def.Tm[Chl][Z_curr].C[7],10,8);
  cvtfc(main_var11,def.Tm[Chl][Z_curr].C[8],10,8);
  cvtfc(main_var12,def.Tm[Chl][Z_curr].C[9],10,8);
  cvtfc(main_var13,def.Tm[Chl][Z_curr].C[10],10,8);
  cvtfc(main_var14,def.Tm[Chl][Z_curr].Lam[0],10,8);
  cvtfc(main_var15,def.Tm[Chl][Z_curr].Lam[1],10,8);
  cvtfc(main_var16,def.Tm[Chl][Z_curr].Lam[2],10,8);
  cvtfc(main_var17,def.Tm[Chl][Z_curr].Lam[3],10,8);
  cvtfc(main_var18,def.Tm[Chl][Z_curr].Lam[4],10,8);
  cvtfc(main_var19,def.Tm[Chl][Z_curr].Lam[5],10,8);
  cvtfc(main_var20,def.Tm[Chl][Z_curr].Lam[6],10,8);
  cvtfc(main_var21,def.Tm[Chl][Z_curr].Lam[7],10,8);
  cvtfc(main_var22,def.Tm[Chl][Z_curr].Lam[8],10,8);
  cvtfc(main_var23,def.Tm[Chl][Z_curr].Lam[9],10,8);
 return;
}
LCL VOID CTYP _main_2VAL(NOARG)
{
    def.Tm[Chl][Z_curr].p=cvtci(main_var1);
    def.Tm[Chl][Z_curr].E=cvtcf(main_var2);
    def.Tm[Chl][Z_curr].C[0]=cvtcf(main_var3);
    def.Tm[Chl][Z_curr].C[1]=cvtcf(main_var4);
    def.Tm[Chl][Z_curr].C[2]=cvtcf(main_var5);
    def.Tm[Chl][Z_curr].C[3]=cvtcf(main_var6);
    def.Tm[Chl][Z_curr].C[4]=cvtcf(main_var7);
    def.Tm[Chl][Z_curr].C[5]=cvtcf(main_var8);
    def.Tm[Chl][Z_curr].C[6]=cvtcf(main_var9);
    def.Tm[Chl][Z_curr].C[7]=cvtcf(main_var10);
    def.Tm[Chl][Z_curr].C[8]=cvtcf(main_var11);
    def.Tm[Chl][Z_curr].C[9]=cvtcf(main_var12);
    def.Tm[Chl][Z_curr].C[10]=cvtcf(main_var13);
    def.Tm[Chl][Z_curr].Lam[0]=cvtcf(main_var14);
    def.Tm[Chl][Z_curr].Lam[1]=cvtcf(main_var15);
    def.Tm[Chl][Z_curr].Lam[2]=cvtcf(main_var16);
    def.Tm[Chl][Z_curr].Lam[3]=cvtcf(main_var17);
    def.Tm[Chl][Z_curr].Lam[4]=cvtcf(main_var18);
    def.Tm[Chl][Z_curr].Lam[5]=cvtcf(main_var19);
    def.Tm[Chl][Z_curr].Lam[6]=cvtcf(main_var20);
    def.Tm[Chl][Z_curr].Lam[7]=cvtcf(main_var21);
    def.Tm[Chl][Z_curr].Lam[8]=cvtcf(main_var22);
    def.Tm[Chl][Z_curr].Lam[9]=cvtcf(main_var23);
 return;
}

VOID CTYP TESTPARM(NOARG)
{
{
 EdfP e=EctlCur;
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

 _main_OPEN();
 _main_2STR();
 if(e) EntPush();
 EntBuild(&_main_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_main_Fld[0].ftag);
 if(val!=ERR_ARG)
    {
    _main_2VAL();
    EntResult=1;
    }
 CurHide();
 if(e) EntPop();
 KbndFre();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}
  return;
}

/*** END OF FILE ***/
