

/*
 *   Generated by  UI v2.00
 *        June 2, 1995
 */


/* Module: WZK.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* ØÆ´Æ¶•≠®• Æ™≠†    */
         IntT MniC,MniR,MaxC,MaxR;   /* ¢Æß¨Æ¶≠Î• ‡†ß¨•‡Î */
         BytT FrmT;                  /* ‚®Ø °Æ‡§Ó‡†       */
         AtrT FrmA;                  /* †‚‡®°„‚Î °Æ‡§Ó‡†  */
         AtrT Dat;                   /* †‚‡®°„‚Î ‚•™·‚†   */
         BytT Shadow;                /* ‚•≠Ï              */
         AtrT Sat;                   /* Ê¢•‚ ‚•≠®         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "upi_3w.h"

VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_OPEN(NOARG);


LCL ChrT main_var1[6];
LCL ChrT main_var2[6];
LCL ChrT main_var3[6];
LCL ChrT main_var4[6];
LCL ChrT main_var5[6];
LCL ChrT main_var6[6];
LCL ChrT main_var7[6];
LCL ChrT main_var8[6];
LCL ChrT main_var9[6];
LCL ChrT main_var10[6];
LCL ChrT main_var11[6];
LCL ChrT main_var12[6];
LCL ChrT main_var13[6];
LCL ChrT main_var14[6];
LCL ChrT main_var15[6];
LCL ChrT main_var16[6];
LCL ChrT main_var17[6];
LCL ChrT main_var18[6];
LCL ChrT main_var19[6];
LCL ChrT main_var20[6];
LCL ChrT main_var21[6];
LCL ChrT main_var22[6];
LCL ChrT main_var23[6];
LCL ChrT main_var24[6];
LCL ChrT main_var25[6];
LCL ChrT main_var26[6];
LCL ChrT main_var27[6];
LCL ChrT main_var28[6];
LCL ChrT main_var29[6];
LCL ChrT main_var30[6];
LCL ChrT main_var31[6];
LCL ChrT main_var32[6];
LCL ChrT main_var33[6];
LCL ChrT main_var34[6];
LCL ChrT main_var35[6];
LCL ChrT main_var36[6];
LCL ChrT main_var37[6];
LCL ChrT main_var38[6];
LCL ChrT main_var39[6];
LCL ChrT main_var40[6];
LCL ChrT main_var41[6];
LCL ChrT main_var42[6];
LCL ChrT main_var43[6];
LCL ChrT main_var44[6];
LCL ChrT main_var45[6];
LCL ChrT main_var46[6];
LCL ChrT main_var47[6];
LCL ChrT main_var48[6];
LCL ChrT main_var49[6];
LCL ChrT main_var50[6];
LCL ChrT main_var51[6];
LCL ChrT main_var52[6];
LCL ChrT main_var53[6];
LCL ChrT main_var54[6];
LCL ChrT main_var55[6];
LCL ChrT main_var56[6];
LCL ChrT main_var57[6];
LCL ChrT main_var58[6];
LCL ChrT main_var59[6];
LCL ChrT main_var60[6];
LCL ChrT main_var61[6];
LCL ChrT main_var62[6];
LCL ChrT main_var63[6];
LCL ChrT main_var64[6];
LCL ChrT main_var65[6];
LCL ChrT main_var66[6];
LCL ChrT main_var67[6];
LCL ChrT main_var68[6];
LCL ChrT main_var69[6];
LCL ChrT main_var70[6];
LCL ChrT main_var71[6];
LCL ChrT main_var72[6];
LCL ChrT main_var73[6];
LCL ChrT main_var74[6];
LCL ChrT main_var75[6];
LCL ChrT main_var76[6];
LCL ChrT main_var77[6];
LCL ChrT main_var78[6];
LCL ChrT main_var79[6];
LCL ChrT main_var80[6];
LCL ChrT main_var81[6];
LCL ChrT main_var82[6];
LCL ChrT main_var83[6];
LCL ChrT main_var84[6];
LCL ChrT main_var85[6];
LCL ChrT main_var86[6];
LCL ChrT main_var87[6];
LCL ChrT main_var88[6];
LCL ChrT main_var89[6];
LCL ChrT main_var90[6];
LCL ChrT main_var91[6];
LCL ChrT main_var92[6];
LCL ChrT main_var93[6];
LCL ChrT main_var94[6];
LCL ChrT main_var95[6];
LCL ChrT main_var96[6];
LCL ChrT main_var97[6];
LCL ChrT main_var98[6];
LCL ChrT main_var99[6];
LCL ChrT main_var100[6];
LCL FbldT _main_Fld[]={
 {"",0,0, main_var1,2,6,
  "99.99",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var2,2,12,
  "99.99",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var3,2,18,
  "99.99",NULL,NULL,NULL,
  0,3,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var4,2,24,
  "99.99",NULL,NULL,NULL,
  0,4,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var5,2,30,
  "99.99",NULL,NULL,NULL,
  0,5,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var6,2,36,
  "99.99",NULL,NULL,NULL,
  0,6,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var7,2,42,
  "99.99",NULL,NULL,NULL,
  0,7,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var8,2,48,
  "99.99",NULL,NULL,NULL,
  0,8,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var9,2,54,
  "99.99",NULL,NULL,NULL,
  0,9,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var10,2,60,
  "99.99",NULL,NULL,NULL,
  0,10,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var11,3,6,
  "99.99",NULL,NULL,NULL,
  0,11,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var12,3,12,
  "99.99",NULL,NULL,NULL,
  0,12,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var13,3,18,
  "99.99",NULL,NULL,NULL,
  0,13,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var14,3,24,
  "99.99",NULL,NULL,NULL,
  0,14,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var15,3,30,
  "99.99",NULL,NULL,NULL,
  0,15,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var16,3,36,
  "99.99",NULL,NULL,NULL,
  0,16,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var17,3,42,
  "99.99",NULL,NULL,NULL,
  0,17,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var18,3,48,
  "99.99",NULL,NULL,NULL,
  0,18,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var19,3,54,
  "99.99",NULL,NULL,NULL,
  0,19,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var20,3,60,
  "99.99",NULL,NULL,NULL,
  0,20,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var21,4,6,
  "99.99",NULL,NULL,NULL,
  0,21,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var22,4,12,
  "99.99",NULL,NULL,NULL,
  0,22,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var23,4,18,
  "99.99",NULL,NULL,NULL,
  0,23,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var24,4,24,
  "99.99",NULL,NULL,NULL,
  0,24,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var25,4,30,
  "99.99",NULL,NULL,NULL,
  0,25,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var26,4,36,
  "99.99",NULL,NULL,NULL,
  0,26,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var27,4,42,
  "99.99",NULL,NULL,NULL,
  0,27,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var28,4,48,
  "99.99",NULL,NULL,NULL,
  0,28,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var29,4,54,
  "99.99",NULL,NULL,NULL,
  0,29,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var30,4,60,
  "99.99",NULL,NULL,NULL,
  0,30,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var31,5,6,
  "99.99",NULL,NULL,NULL,
  0,31,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var32,5,12,
  "99.99",NULL,NULL,NULL,
  0,32,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var33,5,18,
  "99.99",NULL,NULL,NULL,
  0,33,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var34,5,24,
  "99.99",NULL,NULL,NULL,
  0,34,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var35,5,30,
  "99.99",NULL,NULL,NULL,
  0,35,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var36,5,36,
  "99.99",NULL,NULL,NULL,
  0,36,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var37,5,42,
  "99.99",NULL,NULL,NULL,
  0,37,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var38,5,48,
  "99.99",NULL,NULL,NULL,
  0,38,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var39,5,54,
  "99.99",NULL,NULL,NULL,
  0,39,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var40,5,60,
  "99.99",NULL,NULL,NULL,
  0,40,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var41,6,6,
  "99.99",NULL,NULL,NULL,
  0,41,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var42,6,12,
  "99.99",NULL,NULL,NULL,
  0,42,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var43,6,18,
  "99.99",NULL,NULL,NULL,
  0,43,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var44,6,24,
  "99.99",NULL,NULL,NULL,
  0,44,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var45,6,30,
  "99.99",NULL,NULL,NULL,
  0,45,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var46,6,36,
  "99.99",NULL,NULL,NULL,
  0,46,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var47,6,42,
  "99.99",NULL,NULL,NULL,
  0,47,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var48,6,48,
  "99.99",NULL,NULL,NULL,
  0,48,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var49,6,54,
  "99.99",NULL,NULL,NULL,
  0,49,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var50,6,60,
  "99.99",NULL,NULL,NULL,
  0,50,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var51,7,6,
  "99.99",NULL,NULL,NULL,
  0,51,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var52,7,12,
  "99.99",NULL,NULL,NULL,
  0,52,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var53,7,18,
  "99.99",NULL,NULL,NULL,
  0,53,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var54,7,24,
  "99.99",NULL,NULL,NULL,
  0,54,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var55,7,30,
  "99.99",NULL,NULL,NULL,
  0,55,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var56,7,36,
  "99.99",NULL,NULL,NULL,
  0,56,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var57,7,42,
  "99.99",NULL,NULL,NULL,
  0,57,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var58,7,48,
  "99.99",NULL,NULL,NULL,
  0,58,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var59,7,54,
  "99.99",NULL,NULL,NULL,
  0,59,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var60,7,60,
  "99.99",NULL,NULL,NULL,
  0,60,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var61,8,6,
  "99.99",NULL,NULL,NULL,
  0,61,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var62,8,12,
  "99.99",NULL,NULL,NULL,
  0,62,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var63,8,18,
  "99.99",NULL,NULL,NULL,
  0,63,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var64,8,24,
  "99.99",NULL,NULL,NULL,
  0,64,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var65,8,30,
  "99.99",NULL,NULL,NULL,
  0,65,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var66,8,36,
  "99.99",NULL,NULL,NULL,
  0,66,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var67,8,42,
  "99.99",NULL,NULL,NULL,
  0,67,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var68,8,48,
  "99.99",NULL,NULL,NULL,
  0,68,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var69,8,54,
  "99.99",NULL,NULL,NULL,
  0,69,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var70,8,60,
  "99.99",NULL,NULL,NULL,
  0,70,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var71,9,6,
  "99.99",NULL,NULL,NULL,
  0,71,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var72,9,12,
  "99.99",NULL,NULL,NULL,
  0,72,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var73,9,18,
  "99.99",NULL,NULL,NULL,
  0,73,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var74,9,24,
  "99.99",NULL,NULL,NULL,
  0,74,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var75,9,30,
  "99.99",NULL,NULL,NULL,
  0,75,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var76,9,36,
  "99.99",NULL,NULL,NULL,
  0,76,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var77,9,42,
  "99.99",NULL,NULL,NULL,
  0,77,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var78,9,48,
  "99.99",NULL,NULL,NULL,
  0,78,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var79,9,54,
  "99.99",NULL,NULL,NULL,
  0,79,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var80,9,60,
  "99.99",NULL,NULL,NULL,
  0,80,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var81,10,6,
  "99.99",NULL,NULL,NULL,
  0,81,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var82,10,12,
  "99.99",NULL,NULL,NULL,
  0,82,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var83,10,18,
  "99.99",NULL,NULL,NULL,
  0,83,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var84,10,24,
  "99.99",NULL,NULL,NULL,
  0,84,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var85,10,30,
  "99.99",NULL,NULL,NULL,
  0,85,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var86,10,36,
  "99.99",NULL,NULL,NULL,
  0,86,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var87,10,42,
  "99.99",NULL,NULL,NULL,
  0,87,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var88,10,48,
  "99.99",NULL,NULL,NULL,
  0,88,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var89,10,54,
  "99.99",NULL,NULL,NULL,
  0,89,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var90,10,60,
  "99.99",NULL,NULL,NULL,
  0,90,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var91,11,6,
  "99.99",NULL,NULL,NULL,
  0,91,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var92,11,12,
  "99.99",NULL,NULL,NULL,
  0,92,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var93,11,18,
  "99.99",NULL,NULL,NULL,
  0,93,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var94,11,24,
  "99.99",NULL,NULL,NULL,
  0,94,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var95,11,30,
  "99.99",NULL,NULL,NULL,
  0,95,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var96,11,36,
  "99.99",NULL,NULL,NULL,
  0,96,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var97,11,42,
  "99.99",NULL,NULL,NULL,
  0,97,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var98,11,48,
  "99.99",NULL,NULL,NULL,
  0,98,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var99,11,54,
  "99.99",NULL,NULL,NULL,
  0,99,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var100,11,60,
  "99.99",NULL,NULL,NULL,
  0,100,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _main_Frm={
 _main_Fld,100,NULL,NULL,101,0|ENT_DIR|ENT_WRP,
 0,_CYAN|BLACK,_LGREY|BLACK,_LGREY|BLACK
};
LCL VOID CTYP _main_OPEN(NOARG)
{

 Wopen(3,5,17,74,BOX_SNG,
       _CYAN|INTENSE|LGREY,_CYAN|BLACK);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,16,_CYAN|INTENSE|LGREY,'¥');
  Wmessage(" äÆÌ‰‰®Ê®•≠‚Î ¢ß†®¨Æ¢´®Ô≠®Ô ™†≠†´Æ¢ ",BRD_TOP,17,_LGREY|BLACK);
  Wbprintc(BRD_TOP,53,_CYAN|INTENSE|LGREY,'√');
  Wbprintc(BRD_BOT,8,_CYAN|INTENSE|LGREY,' ');
  Wmessage("Alt+<N>",BRD_BOT,9,_CYAN|BROWN);
  Wmessage("-è•‡•©‚® ™ ™†≠†´„ <N> ",BRD_BOT,16,_CYAN|INTENSE|BLACK);
  Wmessage(" Ctrl+Enter",BRD_BOT,38,_CYAN|BROWN);
  Wmessage("-á†ØÆ¨≠®‚Ï",BRD_BOT,49,_CYAN|INTENSE|BLACK);
  Wbprintc(BRD_BOT,59,_CYAN|INTENSE|LGREY,' ');
  Wprts(0,1,_CYAN|BLACK,"NN");
  Wprts(0,5,_CYAN|BLACK,"≥");
  Wprts(0,8,_CYAN|BLACK,"1");
  Wprts(0,14,_CYAN|BLACK,"2");
  Wprts(0,20,_CYAN|BLACK,"3");
  Wprts(0,26,_CYAN|BLACK,"4");
  Wprts(0,32,_CYAN|BLACK,"5");
  Wprts(0,38,_CYAN|BLACK,"6");
  Wprts(0,44,_CYAN|BLACK,"7");
  Wprts(0,50,_CYAN|BLACK,"8");
  Wprts(0,56,_CYAN|BLACK,"9");
  Wprts(0,61,_CYAN|BLACK,"10");
  Wprts(1,0,_CYAN|BLACK,"ƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ");
  Wprts(2,2,_CYAN|BLACK,"1");
  Wprts(2,5,_CYAN|BLACK,"≥");
  Wprts(3,2,_CYAN|BLACK,"2");
  Wprts(3,5,_CYAN|BLACK,"≥");
  Wprts(4,2,_CYAN|BLACK,"3");
  Wprts(4,5,_CYAN|BLACK,"≥");
  Wprts(5,2,_CYAN|BLACK,"4");
  Wprts(5,5,_CYAN|BLACK,"≥");
  Wprts(6,2,_CYAN|BLACK,"5");
  Wprts(6,5,_CYAN|BLACK,"≥");
  Wprts(7,2,_CYAN|BLACK,"6");
  Wprts(7,5,_CYAN|BLACK,"≥");
  Wprts(8,2,_CYAN|BLACK,"7");
  Wprts(8,5,_CYAN|BLACK,"≥");
  Wprts(9,2,_CYAN|BLACK,"8");
  Wprts(9,5,_CYAN|BLACK,"≥");
  Wprts(10,2,_CYAN|BLACK,"9");
  Wprts(10,5,_CYAN|BLACK,"≥");
  Wprts(11,1,_CYAN|BLACK,"10");
  Wprts(11,5,_CYAN|BLACK,"≥");
  Wprts(12,5,_CYAN|BLACK,"≥");

  _main_2STR();
  EntPush();
  EntBuild(&_main_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _main_2STR(NOARG)
{
  cvtfc(main_var1,def.wzk[0][0],5,2);
  cvtfc(main_var2,def.wzk[0][1],5,2);
  cvtfc(main_var3,def.wzk[0][2],5,2);
  cvtfc(main_var4,def.wzk[0][3],5,2);
  cvtfc(main_var5,def.wzk[0][4],5,2);
  cvtfc(main_var6,def.wzk[0][5],5,2);
  cvtfc(main_var7,def.wzk[0][6],5,2);
  cvtfc(main_var8,def.wzk[0][7],5,2);
  cvtfc(main_var9,def.wzk[0][8],5,2);
  cvtfc(main_var10,def.wzk[0][9],5,2);
  cvtfc(main_var11,def.wzk[1][0],5,2);
  cvtfc(main_var12,def.wzk[1][1],5,2);
  cvtfc(main_var13,def.wzk[1][2],5,2);
  cvtfc(main_var14,def.wzk[1][3],5,2);
  cvtfc(main_var15,def.wzk[1][4],5,2);
  cvtfc(main_var16,def.wzk[1][5],5,2);
  cvtfc(main_var17,def.wzk[1][6],5,2);
  cvtfc(main_var18,def.wzk[1][7],5,2);
  cvtfc(main_var19,def.wzk[1][8],5,2);
  cvtfc(main_var20,def.wzk[1][9],5,2);
  cvtfc(main_var21,def.wzk[2][0],5,2);
  cvtfc(main_var22,def.wzk[2][1],5,2);
  cvtfc(main_var23,def.wzk[2][2],5,2);
  cvtfc(main_var24,def.wzk[2][3],5,2);
  cvtfc(main_var25,def.wzk[2][4],5,2);
  cvtfc(main_var26,def.wzk[2][5],5,2);
  cvtfc(main_var27,def.wzk[2][6],5,2);
  cvtfc(main_var28,def.wzk[2][7],5,2);
  cvtfc(main_var29,def.wzk[2][8],5,2);
  cvtfc(main_var30,def.wzk[2][9],5,2);
  cvtfc(main_var31,def.wzk[3][0],5,2);
  cvtfc(main_var32,def.wzk[3][1],5,2);
  cvtfc(main_var33,def.wzk[3][2],5,2);
  cvtfc(main_var34,def.wzk[3][3],5,2);
  cvtfc(main_var35,def.wzk[3][4],5,2);
  cvtfc(main_var36,def.wzk[3][5],5,2);
  cvtfc(main_var37,def.wzk[3][6],5,2);
  cvtfc(main_var38,def.wzk[3][7],5,2);
  cvtfc(main_var39,def.wzk[3][8],5,2);
  cvtfc(main_var40,def.wzk[3][9],5,2);
  cvtfc(main_var41,def.wzk[4][0],5,2);
  cvtfc(main_var42,def.wzk[4][1],5,2);
  cvtfc(main_var43,def.wzk[4][2],5,2);
  cvtfc(main_var44,def.wzk[4][3],5,2);
  cvtfc(main_var45,def.wzk[4][4],5,2);
  cvtfc(main_var46,def.wzk[4][5],5,2);
  cvtfc(main_var47,def.wzk[4][6],5,2);
  cvtfc(main_var48,def.wzk[4][7],5,2);
  cvtfc(main_var49,def.wzk[4][8],5,2);
  cvtfc(main_var50,def.wzk[4][9],5,2);
  cvtfc(main_var51,def.wzk[5][0],5,2);
  cvtfc(main_var52,def.wzk[5][1],5,2);
  cvtfc(main_var53,def.wzk[5][2],5,2);
  cvtfc(main_var54,def.wzk[5][3],5,2);
  cvtfc(main_var55,def.wzk[5][4],5,2);
  cvtfc(main_var56,def.wzk[5][5],5,2);
  cvtfc(main_var57,def.wzk[5][6],5,2);
  cvtfc(main_var58,def.wzk[5][7],5,2);
  cvtfc(main_var59,def.wzk[5][8],5,2);
  cvtfc(main_var60,def.wzk[5][9],5,2);
  cvtfc(main_var61,def.wzk[6][0],5,2);
  cvtfc(main_var62,def.wzk[6][1],5,2);
  cvtfc(main_var63,def.wzk[6][2],5,2);
  cvtfc(main_var64,def.wzk[6][3],5,2);
  cvtfc(main_var65,def.wzk[6][4],5,2);
  cvtfc(main_var66,def.wzk[6][5],5,2);
  cvtfc(main_var67,def.wzk[6][6],5,2);
  cvtfc(main_var68,def.wzk[6][7],5,2);
  cvtfc(main_var69,def.wzk[6][8],5,2);
  cvtfc(main_var70,def.wzk[6][9],5,2);
  cvtfc(main_var71,def.wzk[7][0],5,2);
  cvtfc(main_var72,def.wzk[7][1],5,2);
  cvtfc(main_var73,def.wzk[7][2],5,2);
  cvtfc(main_var74,def.wzk[7][3],5,2);
  cvtfc(main_var75,def.wzk[7][4],5,2);
  cvtfc(main_var76,def.wzk[7][5],5,2);
  cvtfc(main_var77,def.wzk[7][6],5,2);
  cvtfc(main_var78,def.wzk[7][7],5,2);
  cvtfc(main_var79,def.wzk[7][8],5,2);
  cvtfc(main_var80,def.wzk[7][9],5,2);
  cvtfc(main_var81,def.wzk[8][0],5,2);
  cvtfc(main_var82,def.wzk[8][1],5,2);
  cvtfc(main_var83,def.wzk[8][2],5,2);
  cvtfc(main_var84,def.wzk[8][3],5,2);
  cvtfc(main_var85,def.wzk[8][4],5,2);
  cvtfc(main_var86,def.wzk[8][5],5,2);
  cvtfc(main_var87,def.wzk[8][6],5,2);
  cvtfc(main_var88,def.wzk[8][7],5,2);
  cvtfc(main_var89,def.wzk[8][8],5,2);
  cvtfc(main_var90,def.wzk[8][9],5,2);
  cvtfc(main_var91,def.wzk[9][0],5,2);
  cvtfc(main_var92,def.wzk[9][1],5,2);
  cvtfc(main_var93,def.wzk[9][2],5,2);
  cvtfc(main_var94,def.wzk[9][3],5,2);
  cvtfc(main_var95,def.wzk[9][4],5,2);
  cvtfc(main_var96,def.wzk[9][5],5,2);
  cvtfc(main_var97,def.wzk[9][6],5,2);
  cvtfc(main_var98,def.wzk[9][7],5,2);
  cvtfc(main_var99,def.wzk[9][8],5,2);
  cvtfc(main_var100,def.wzk[9][9],5,2);
 return;
}
LCL VOID CTYP _main_2VAL(NOARG)
{
    def.wzk[0][0]=cvtcf(main_var1);
    def.wzk[0][1]=cvtcf(main_var2);
    def.wzk[0][2]=cvtcf(main_var3);
    def.wzk[0][3]=cvtcf(main_var4);
    def.wzk[0][4]=cvtcf(main_var5);
    def.wzk[0][5]=cvtcf(main_var6);
    def.wzk[0][6]=cvtcf(main_var7);
    def.wzk[0][7]=cvtcf(main_var8);
    def.wzk[0][8]=cvtcf(main_var9);
    def.wzk[0][9]=cvtcf(main_var10);
    def.wzk[1][0]=cvtcf(main_var11);
    def.wzk[1][1]=cvtcf(main_var12);
    def.wzk[1][2]=cvtcf(main_var13);
    def.wzk[1][3]=cvtcf(main_var14);
    def.wzk[1][4]=cvtcf(main_var15);
    def.wzk[1][5]=cvtcf(main_var16);
    def.wzk[1][6]=cvtcf(main_var17);
    def.wzk[1][7]=cvtcf(main_var18);
    def.wzk[1][8]=cvtcf(main_var19);
    def.wzk[1][9]=cvtcf(main_var20);
    def.wzk[2][0]=cvtcf(main_var21);
    def.wzk[2][1]=cvtcf(main_var22);
    def.wzk[2][2]=cvtcf(main_var23);
    def.wzk[2][3]=cvtcf(main_var24);
    def.wzk[2][4]=cvtcf(main_var25);
    def.wzk[2][5]=cvtcf(main_var26);
    def.wzk[2][6]=cvtcf(main_var27);
    def.wzk[2][7]=cvtcf(main_var28);
    def.wzk[2][8]=cvtcf(main_var29);
    def.wzk[2][9]=cvtcf(main_var30);
    def.wzk[3][0]=cvtcf(main_var31);
    def.wzk[3][1]=cvtcf(main_var32);
    def.wzk[3][2]=cvtcf(main_var33);
    def.wzk[3][3]=cvtcf(main_var34);
    def.wzk[3][4]=cvtcf(main_var35);
    def.wzk[3][5]=cvtcf(main_var36);
    def.wzk[3][6]=cvtcf(main_var37);
    def.wzk[3][7]=cvtcf(main_var38);
    def.wzk[3][8]=cvtcf(main_var39);
    def.wzk[3][9]=cvtcf(main_var40);
    def.wzk[4][0]=cvtcf(main_var41);
    def.wzk[4][1]=cvtcf(main_var42);
    def.wzk[4][2]=cvtcf(main_var43);
    def.wzk[4][3]=cvtcf(main_var44);
    def.wzk[4][4]=cvtcf(main_var45);
    def.wzk[4][5]=cvtcf(main_var46);
    def.wzk[4][6]=cvtcf(main_var47);
    def.wzk[4][7]=cvtcf(main_var48);
    def.wzk[4][8]=cvtcf(main_var49);
    def.wzk[4][9]=cvtcf(main_var50);
    def.wzk[5][0]=cvtcf(main_var51);
    def.wzk[5][1]=cvtcf(main_var52);
    def.wzk[5][2]=cvtcf(main_var53);
    def.wzk[5][3]=cvtcf(main_var54);
    def.wzk[5][4]=cvtcf(main_var55);
    def.wzk[5][5]=cvtcf(main_var56);
    def.wzk[5][6]=cvtcf(main_var57);
    def.wzk[5][7]=cvtcf(main_var58);
    def.wzk[5][8]=cvtcf(main_var59);
    def.wzk[5][9]=cvtcf(main_var60);
    def.wzk[6][0]=cvtcf(main_var61);
    def.wzk[6][1]=cvtcf(main_var62);
    def.wzk[6][2]=cvtcf(main_var63);
    def.wzk[6][3]=cvtcf(main_var64);
    def.wzk[6][4]=cvtcf(main_var65);
    def.wzk[6][5]=cvtcf(main_var66);
    def.wzk[6][6]=cvtcf(main_var67);
    def.wzk[6][7]=cvtcf(main_var68);
    def.wzk[6][8]=cvtcf(main_var69);
    def.wzk[6][9]=cvtcf(main_var70);
    def.wzk[7][0]=cvtcf(main_var71);
    def.wzk[7][1]=cvtcf(main_var72);
    def.wzk[7][2]=cvtcf(main_var73);
    def.wzk[7][3]=cvtcf(main_var74);
    def.wzk[7][4]=cvtcf(main_var75);
    def.wzk[7][5]=cvtcf(main_var76);
    def.wzk[7][6]=cvtcf(main_var77);
    def.wzk[7][7]=cvtcf(main_var78);
    def.wzk[7][8]=cvtcf(main_var79);
    def.wzk[7][9]=cvtcf(main_var80);
    def.wzk[8][0]=cvtcf(main_var81);
    def.wzk[8][1]=cvtcf(main_var82);
    def.wzk[8][2]=cvtcf(main_var83);
    def.wzk[8][3]=cvtcf(main_var84);
    def.wzk[8][4]=cvtcf(main_var85);
    def.wzk[8][5]=cvtcf(main_var86);
    def.wzk[8][6]=cvtcf(main_var87);
    def.wzk[8][7]=cvtcf(main_var88);
    def.wzk[8][8]=cvtcf(main_var89);
    def.wzk[8][9]=cvtcf(main_var90);
    def.wzk[9][0]=cvtcf(main_var91);
    def.wzk[9][1]=cvtcf(main_var92);
    def.wzk[9][2]=cvtcf(main_var93);
    def.wzk[9][3]=cvtcf(main_var94);
    def.wzk[9][4]=cvtcf(main_var95);
    def.wzk[9][5]=cvtcf(main_var96);
    def.wzk[9][6]=cvtcf(main_var97);
    def.wzk[9][7]=cvtcf(main_var98);
    def.wzk[9][8]=cvtcf(main_var99);
    def.wzk[9][9]=cvtcf(main_var100);
 return;
}

VOID CTYP WZK(NOARG)
{
{
 IntT val,tmp=EntResult;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _main_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _main_2STR();
 EntPush();
 EntBuild(&_main_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_main_Fld[0].ftag);
 if(val!=ERR_ARG)
    {
    _main_2VAL();
    EntResult=1;
    }
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 EntResult=tmp;
}
  return;
}

/*** END OF FILE ***/
