
// Определения новых команд TV
const int cmLoadEmul=200,               hcLoadEmul=200,
          cmSaveEmul=201,               hcSaveEmul=201,
          cmSaveEmulAs=202,
          cmInsChannel=203,             hcInsChannel=203,
          cmDelChannel=204,             hcDelChannel=204,
          cmXrefChannel=205,            hcXrefChannel=205,
          cmInsZveno=206,               hcInsZveno=206,
          cmDelZveno=207,               hcDelZveno=207,
          cmDefZveno=208,               hcDefZveno=208,
          cmACX=209,                    hcACX=209,
          cmPulse=210,                  hcPulse=210,
          cmSinus=211,                  hcSinus=211,
                                        hcCascade=212,
          cmWinList=213,                hcWindow=213,

          cmCloseEmul=214,
          cmOpenEmul=215,
          cmEditChannel=216
          ;

