

/*
 *   Generated by  UI v2.00
 *        October 24, 1997
 */


/* Module: MNUVIEW.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>
#include <tcxladd.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include  "view.h"

VOID  CTYP _title_WRITE(NOARG);
KeyT  CTYP _upr_type_MENU(NOARG);
VOID  CTYP _upr_SELECT(NOARG);
VOID  CTYP _tem_SELECT(NOARG);
VOID  CTYP _sth_SELECT(NOARG);
VOID  CTYP _ach_SELECT(NOARG);
VOID  CTYP _upr_do_EXEC(NOARG);
VOID  CTYP _tem_do_EXEC(NOARG);
VOID  CTYP _sth_do_EXEC(NOARG);
VOID  CTYP _ach_do_EXEC(NOARG);
VOID CTYP _background_2STR(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);
VOID CTYP _title_2STR(NOARG);
VOID CTYP _upr_type_2STR(NOARG);
VOID CTYP _upr_type_MSG(NOARG);
VOID CTYP _upr_2STR(NOARG);
VOID CTYP _upr_MSG(NOARG);
VOID CTYP _tem_2STR(NOARG);
VOID CTYP _tem_MSG(NOARG);
VOID CTYP _sth_2STR(NOARG);
VOID CTYP _sth_MSG(NOARG);
VOID CTYP _ach_2STR(NOARG);
VOID CTYP _ach_MSG(NOARG);


LCL IbldT _main_Itm[]={
{"     Протокол испытания     ",'\0',ITM_NOR,1,1,  1,HLP_NONE,
   0,2,NULL,_upr_SELECT,NULL,
   NULL,NULL},
{"      Эталонный сигнал      ",'\0',ITM_NOR,2,1,  3,HLP_NONE,
   0,4,NULL,_tem_SELECT,NULL,
   NULL,NULL},
{" Статические характеристики ",'\0',ITM_NOR,6,1,  5,HLP_NONE,
   0,6,NULL,_sth_SELECT,NULL,
   NULL,NULL},
{"            АЧХ             ",'\0',ITM_NOR,7,1,  7,HLP_NONE,
   0,8,NULL,_ach_SELECT,NULL,
   NULL,NULL},
{"      Закончить работу      ",'\0',ITM_NOR,12,1,  9,HLP_NONE,
   0,10,NULL,NULL,NULL,
   NULL,NULL},
};


LCL VOID CTYP _main_MSG(NOARG);
LCL MbldT _main_Mnu={
   _main_Itm,5,7,24,21,55,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_VER,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|CYAN,_BLUE|INTENSE|CYAN,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_CYAN|INTENSE|LGREY,
   0,_main_MSG,11, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _main_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage(" Система нагружения ",BRD_TOP,6,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_LFT,5,_BLUE|INTENSE|LGREY,'╟');
  Wbprintc(BRD_LFT,12,_BLUE|INTENSE|LGREY,'╟');
  Wbprintc(BRD_RGT,5,_BLUE|INTENSE|LGREY,'╢');
  Wbprintc(BRD_RGT,12,_BLUE|INTENSE|LGREY,'╢');
  Wprts(3,1,_BLUE|LGREY," ");
  Wprts(4,0,_BLUE|INTENSE|LGREY,"─── Характеристики обьекта ───");
  Wprts(5,1,_BLUE|LGREY," ");
  Wprts(8,1,_BLUE|LGREY,"  ");
  Wprts(8,3,_BLUE|CYAN,"Взаимодействие в статике");
  Wprts(8,27,_BLUE|LGREY," ");
  Wprts(9,2,_BLUE|CYAN,"Взаимодействие  в динамике");
  Wprts(11,0,_BLUE|INTENSE|LGREY,"──────────────────────────────");
  {
  MnuDsp(&_main_Mnu);
  }
  return;
}
LCL VOID CTYP _title_WRITE(NOARG)
{
 Wopen(1,14,6,64,BOX_SNG,
       _BROWN|INTENSE|LGREY,_BROWN|INTENSE|LGREY);
 CurHide();
  Wprts(0,20,_BROWN|INTENSE|LGREY,"ПРОСМОТР");
  Wprts(1,8,_BROWN|INTENSE|LGREY,"результатов");
  Wprts(1,20,_BROWN|INTENSE|LGREY,"проведения");
  Wprts(1,31,_BROWN|INTENSE|LGREY,"испытаний");
  Wprts(2,2,_BROWN|INTENSE|LGREY,"с");
  Wprts(2,4,_BROWN|INTENSE|LGREY,"использованием");
  Wprts(2,19,_BROWN|INTENSE|CYAN,"АДАПТИВНОЙ СИСТЕМЫ УПРАВЛЕНИЯ");
  Wprts(3,15,_BROWN|INTENSE|LGREY,"в");
  Wprts(3,17,_BROWN|INTENSE|LGREY,"графическом");
  Wprts(3,29,_BROWN|INTENSE|LGREY,"виде");
 Wunlink(Whandle());
 return;
}

LCL VOID CTYP _opt3_ACT(NOARG)
{
Sel=2;
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
Sel=1;
return;
}

LCL IbldT _upr_type_Itm[]={
{"    Отклик/эталон     ",'\0',ITM_NOR|ITM_AFT,1,1,  12,HLP_NONE,
   0,13,NULL,_opt3_ACT,NULL,
   NULL,NULL},
{"  Управление/отклик   ",'\0',ITM_NOR|ITM_AFT,2,1,  14,HLP_NONE,
   0,15,NULL,_opt4_ACT,NULL,
   NULL,NULL},
};


LCL VOID CTYP _upr_type_MSG(NOARG);
LCL MbldT _upr_type_Mnu={
   _upr_type_Itm,2,10,27,15,52,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_VER,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|CYAN,_BLUE|INTENSE|CYAN,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_CYAN|INTENSE|LGREY,
   0,_upr_type_MSG,16, 0,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _upr_type_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  {
  MnuDsp(&_upr_type_Mnu);
  }
  return;
}
LCL KeyT CTYP _upr_type_MENU(NOARG)
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_upr_type_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
 return ret;
}
LCL VOID CTYP _upr_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL VOID CTYP _upr_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP upr_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOn();
  SelParOn();
  upr_file=SelFile(11,27,23,65,BOX_HOR,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_LGREY|BLACK,
          1,"*.UPR",_upr_MSG);
   if(upr_file!=NULL)
     {
     strcpy(upr_filename,upr_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _upr_do_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _tem_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL VOID CTYP _tem_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP tem_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOn();
  SelParOn();
  tem_file=SelFile(11,27,23,65,BOX_HOR,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_LGREY|BLACK,
          1,"*.TEM",_tem_MSG);
   if(tem_file!=NULL)
     {
     strcpy(tem_filename,tem_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _tem_do_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _sth_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL VOID CTYP _sth_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP sth_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOn();
  SelParOn();
  sth_file=SelFile(11,27,23,65,BOX_HOR,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_LGREY|BLACK,
          1,"*.STH",_sth_MSG);
   if(sth_file!=NULL)
     {
     strcpy(sth_filename,sth_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _sth_do_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _ach_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  return;
}
LCL VOID CTYP _ach_SELECT(NOARG)
{
 IntT tmp=EntResult;
 ChrP ach_file;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);

  EntResult=0;
  SelBarOff();
  SelDirOn();
  SelParOn();
  ach_file=SelFile(11,27,23,65,BOX_HOR,_GREEN|INTENSE|LGREY,_GREEN|INTENSE|LGREY,_LGREY|BLACK,
          1,"*.ACH",_ach_MSG);
   if(ach_file!=NULL)
     {
     strcpy(ach_filename,ach_file);
     SelFree();
     EntResult=1;
     }

 KbndFre();
 KbndChg(tcxl_old_kb);
  _ach_do_EXEC();
 EntResult=tmp;
}
LCL VOID CTYP _upr_do_EXEC(NOARG)
{
if(EntResult) {
  Sel=0; _upr_type_MENU();
  switch(Sel)
    {
    case 1: ViewUPR_XY();
            break;
    case 2: ViewUPR_YYt();
            break;
    }}
  return;
}
LCL VOID CTYP _tem_do_EXEC(NOARG)
{
if(EntResult) ViewTEM();
  return;
}
LCL VOID CTYP _sth_do_EXEC(NOARG)
{
if(EntResult) ViewSTH();
  return;
}
LCL VOID CTYP _ach_do_EXEC(NOARG)
{
if(EntResult) ViewACH();
  return;
}


/*=====================================================================*/


int main(NOARG)
{
 LCL ChrT _RusUpl[0x100]="ЙйЦцУуКкЕеНнГгШшЩщЗзХхЪъФфЫыВвАаПп"
                         "РрОоЛлДдЖжЭэЯяЧчСсМмИиТтЬьБбЮюЁё";
   TcxlInit();
   TcxlKeyOff();
   NlsUpl=_RusUpl;
 Wopen(0,0,24,79,BOX_SPA,
       _CYAN|INTENSE|BLACK,_CYAN|INTENSE|BLACK);
 CurHide();
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
  _title_WRITE();
 KbndFre();
 KbndChg(tcxl_old_kb);
   }
{
 IntT ret;
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);


 MnuBuild(&_main_Mnu);
 ret=MnuGet();
 KbndFre();
 KbndChg(tcxl_old_kb);
// return ret;
}
   Wclose();
  return 0;
}

/*** END OF FILE ***/
