#ifdef USE_GRF
triadGRF grf[20]={
  {HOR_1_2, 0,-1,0,1, getX,NULL,
     NULL,NULL,  0,0,  0,0,
     "Воздействие","[Время]",
     NULL,NULL, grfDOUBLE },
  {{0}, 0,0,0,0, getX,NULL, NULL,NULL, 1,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getX,NULL, NULL,NULL, 2,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getX,NULL, NULL,NULL, 3,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getX,NULL, NULL,NULL, 4,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getX,NULL, NULL,NULL, 5,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getX,NULL, NULL,NULL, 6,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getX,NULL, NULL,NULL, 7,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getX,NULL, NULL,NULL, 8,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getX,NULL, NULL,NULL, 9,0, 0,0, NULL,NULL,NULL,NULL },

  {HOR_2_2, 0,-1,0,1, getY,NULL,
     NULL,NULL,  0,0,  0,0,
     "Отклик","[Время]",
     NULL,NULL, grfDOUBLE },
  {{0}, 0,0,0,0, getY,NULL, NULL,NULL, 1,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getY,NULL, NULL,NULL, 2,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getY,NULL, NULL,NULL, 3,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getY,NULL, NULL,NULL, 4,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getY,NULL, NULL,NULL, 5,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getY,NULL, NULL,NULL, 6,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getY,NULL, NULL,NULL, 7,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getY,NULL, NULL,NULL, 8,0, 0,0, NULL,NULL,NULL,NULL, grfDOUBLE},
  {{0}, 0,0,0,0, getY,NULL, NULL,NULL, 9,0, 0,0, NULL,NULL,NULL,NULL }
 };
#endif
